<?php
declare(strict_types=1);

return [
  '/de/dienstleistungen/klimaanlage-installation/' => [
    'slug'          => 'klimaanlage-installation',
    'path'          => '/de/dienstleistungen/klimaanlage-installation/',
    'breadcrumb'    => 'Klimaanlage montieren',
    'title'         => 'Klimaanlage montieren in Benidorm und Marina Baixa | +QUECLIMA',
    'description'   => 'Klimaanlage montieren in Benidorm und der Marina Baixa für Wohnungen, Ferienwohnungen und Gewerbebetriebe. Besichtigung inklusive, verständliches Angebot.',
    'h1'            => 'Klimaanlage montieren in Benidorm und der Marina Baixa',
    'subtitle'      => 'Wir montieren Split-, Multi-Split- und Kanalsysteme mit Besichtigung, Leistungsberechnung und sorgfältiger Inbetriebnahme.',
    'hero_image'    => '/assets/img/services/service-instalacion-aire-acondicionado.webp',
    'hero_alt'      => 'Klimaanlage montieren in einem Wohnhaus',
    'visual_slot'   => 'servicio-instalacion-hero',
    'image_position'=> 'right center',
    'support_image' => [
      'src'     => '/assets/img/services/service-detail-instalacion-aire-acondicionado.png',
      'alt'     => 'Klimaanlage-Montage mit Innen- und Außengerät',
      'caption' => '',
    ],
    'intro_title'   => 'Eine Anlage, die zum realen Bedarf passt',
    'intro'         => 'Bevor wir ein Gerät empfehlen, besichtigen wir das Objekt: Grundfläche, Ausrichtung, Dämmung, Nutzungsweise, Position des Außengeräts, Kondenswasserableitung und mögliche Lärmprobleme. Ziel ist eine Anlage, die effektiv kühlt, nur die nötige Energie verbraucht und im Alltag komfortabel ist.',
    'bullets_title' => 'Was wir berücksichtigen',
    'bullets'       => [
      'Geeignete Leistung für den Raum, die Nutzung und die Ausrichtung.',
      'Optimale Positionierung von Innen- und Außengerät.',
      'Leitungsführung, Kondensatableitung und saubere Ausführung.',
      'Lautstärke, Energieverbrauch und Wartungsfreundlichkeit.',
      'Inbetriebnahme, Einweisung und Garantie.',
    ],
    'when_title'    => 'Wann sich eine Neuinstallation lohnt',
    'when_items'    => [
      'Wenn das Objekt im Sommer keine angenehme Temperatur erreicht.',
      'Wenn das aktuelle Gerät zu viel verbraucht oder häufig ausfällt.',
      'In Ferienwohnungen, wo Zuverlässigkeit, Bedienbarkeit und geringe Lautstärke entscheidend sind.',
      'Bei Gewerberäumen, die in der Hochsaison durchgängig genutzt werden.',
    ],
    'process_title' => 'Wie wir arbeiten',
    'process_items' => [
      'Wir hören zu und besichtigen den Ort.',
      'Wir berechnen eine realistische Lösung ohne überdimensionierte Geräte.',
      'Wir montieren sorgfältig, testen die Anlage und erklären die Bedienung.',
    ],
    'zones_text'    => 'Wir führen Montagen in Benidorm, Altea, Calpe, Finestrat, La Nucía und anderen Orten der Marina Baixa durch.',
    'faq'           => [
      ['q' => 'Was ist besser: Split, Multi-Split oder Kanal?', 'a' => 'Das hängt vom Objekt, den zu kühlenden Räumen und einer eventuell vorhandenen Vorinstallation ab. Wir klären das vor dem Angebot.'],
      ['q' => 'Kann in Ferienwohnungen montiert werden?', 'a' => 'Ja. Dabei achten wir besonders auf Lautstärke, Energieverbrauch, einfache Bedienung und Zuverlässigkeit in der Hochsaison.'],
      ['q' => 'Ist eine Besichtigung notwendig?', 'a' => 'Empfehlenswert, wenn Fragen zu Leistung, Geräteposition, Ableitung oder Leitungsführung bestehen.'],
    ],
    'cta_event'     => 'cta_quote_service_install_detail',
    'service_type'  => 'Klimaanlage montieren',
  ],
  '/de/dienstleistungen/klimaanlagen-wartung/' => [
    'slug'          => 'klimaanlagen-wartung',
    'path'          => '/de/dienstleistungen/klimaanlagen-wartung/',
    'breadcrumb'    => 'Klimaanlagen-Wartung',
    'title'         => 'Klimaanlagen-Wartung in Benidorm und Marina Baixa | +QUECLIMA',
    'description'   => 'Klimaanlagen-Wartung in Benidorm und der Marina Baixa: Filterreinigung, Geräteinspektion, Ableitung prüfen und Vorbereitung für die Sommersaison.',
    'h1'            => 'Klimaanlagen-Wartung in Benidorm und der Marina Baixa',
    'subtitle'      => 'Wir warten Klimaanlagen, um Ausfälle zu reduzieren, die Leistung zu verbessern und das System vor dem Sommer fit zu machen.',
    'hero_image'    => '/assets/img/services/service-mantenimiento-climatizacion.webp',
    'hero_alt'      => 'Klimaanlagen-Wartung und Geräteinspektion',
    'visual_slot'   => 'servicio-mantenimiento-hero',
    'image_position'=> 'right center',
    'support_image' => [
      'src'     => '/assets/img/services/service-detail-mantenimiento-climatizacion.png',
      'alt'     => 'Klimaanlagen-Wartung und technische Prüfung',
      'caption' => '',
    ],
    'intro_title'   => 'Wartung verlängert die Lebensdauer',
    'intro'         => 'Ein verschmutztes oder schlecht gewartetes Gerät kühlt schlechter, verbraucht mehr Energie und fällt genau dann aus, wenn man es am dringendsten braucht. In Wohnhäusern, Ferienwohnungen, Gemeinschaftsanlagen und Gewerbebetrieben prüfen wir die häufigsten Schwachstellen und informieren klar über Reinigung, Einstellung oder Reparaturbedarf.',
    'bullets_title' => 'Was wir prüfen',
    'bullets'       => [
      'Filterreinigung und allgemeiner Zustand.',
      'Inspektion der Wärmetauscher, Ableitung und möglicher Verstopfungen.',
      'Sichtprüfung der Außengeräte und Belüftung.',
      'Geräusche, Vibrationen, Gerüche oder Wasseraustritt.',
      'Empfehlungen zur Reduzierung von Verbrauch und Verschleiß.',
    ],
    'when_title'    => 'Wann ein Service sinnvoll ist',
    'when_items'    => [
      'Vor der Hitzesaison, besonders bei stark genutzten Objekten.',
      'Wenn das Gerät schwächer kühlt oder länger als früher braucht.',
      'Bei Gerüchen, Tropfen, Geräuschen oder Vibrationen.',
      'In Ferienwohnungen und Gewerbebetrieben mit vielen Betriebsstunden.',
    ],
    'process_title' => 'Wie wir arbeiten',
    'process_items' => [
      'Wir inspizieren das Gerät und nehmen beschriebene Symptome auf.',
      'Wir reinigen und prüfen die wichtigsten zugänglichen Punkte.',
      'Wir teilen mit, ob alles in Ordnung ist oder eine Reparatur ratsam wäre.',
    ],
    'zones_text'    => 'Wir führen Wartungen in Benidorm, Altea, Calpe, Finestrat, La Nucía und umliegenden Orten durch.',
    'faq'           => [
      ['q' => 'Wie oft sollte gewartet werden?', 'a' => 'Das hängt von der Nutzung ab. In Privathaushalten kann ein periodischer Service ausreichen; in Ferienwohnungen und Gewerbebetrieben ist eine Wartung vor jeder Saison meist sinnvoll.'],
      ['q' => 'Verhindert Wartung alle Ausfälle?', 'a' => 'Das lässt sich nicht garantieren, hilft aber, Probleme frühzeitig zu erkennen und Ausfälle durch Verschmutzung, Ableitungsprobleme oder fehlende Wartung zu reduzieren.'],
      ['q' => 'Werden auch Außengeräte gewartet?', 'a' => 'Ja, sofern sie zugänglich und sicher erreichbar sind.'],
    ],
    'cta_event'     => 'cta_quote_service_maintenance_detail',
    'service_type'  => 'Klimaanlagen-Wartung',
  ],
  '/de/dienstleistungen/klimaanlage-reparatur/' => [
    'slug'          => 'klimaanlage-reparatur',
    'path'          => '/de/dienstleistungen/klimaanlage-reparatur/',
    'breadcrumb'    => 'Klimaanlage reparieren',
    'title'         => 'Klimaanlage reparieren in Benidorm und Marina Baixa | +QUECLIMA',
    'description'   => 'Klimaanlage reparieren in Benidorm und der Marina Baixa: kühlt nicht, tropft, macht Geräusche oder zeigt Fehlercodes.',
    'h1'            => 'Klimaanlage reparieren in Benidorm und der Marina Baixa',
    'subtitle'      => 'Wir diagnostizieren Defekte, bevor Teile ausgetauscht oder ein neues Gerät empfohlen wird.',
    'hero_image'    => '/assets/img/services/service-reparacion-aire-acondicionado.webp',
    'hero_alt'      => 'Klimaanlage reparieren und Fehlerdiagnose',
    'visual_slot'   => 'servicio-reparacion-hero',
    'image_position'=> 'right center',
    'support_image' => [
      'src'     => '/assets/img/services/service-detail-reparacion-aire-acondicionado.png',
      'alt'     => 'Klimaanlage-Diagnose und Reparatur',
      'caption' => '',
    ],
    'intro_title'   => 'Klare Diagnose vor der Reparatur',
    'intro'         => 'Wenn ein Gerät nicht mehr kühlt, Wasser austritt, Geräusche macht oder einen Fehlercode anzeigt, ist ein Austausch nicht immer nötig. Wir identifizieren die eigentliche Ursache und erläutern ehrlich, ob Reparatur, Systemeinstellung oder ein Austausch sinnvoll ist.',
    'bullets_title' => 'Häufige Defekte',
    'bullets'       => [
      'Gerät kühlt nicht oder braucht zu lange.',
      'Tropfen, Wasseraustritt oder Ableitungsprobleme.',
      'Geräusche, Vibrationen oder unregelmäßiger Betrieb.',
      'Fehlercodes oder unerwartete Abschaltungen.',
      'Schlechte Leistung durch Verschmutzung, Verschleiß oder verbesserungswürdige Installation.',
    ],
    'when_title'    => 'Wann eine Inspektion sinnvoll ist',
    'when_items'    => [
      'Vor dem Kauf eines neuen Geräts, wenn die Fehlerursache unklar ist.',
      'Wenn warme Luft kommt oder das Gerät läuft, ohne zu stoppen.',
      'Bei Wasserflecken an Wand, Boden oder in der Abtropfwanne.',
      'Wenn sich Geräusche oder Vibrationen gegenüber normalem Betrieb verändert haben.',
    ],
    'process_title' => 'Wie wir arbeiten',
    'process_items' => [
      'Wir nehmen die Symptome auf und inspizieren das Gerät.',
      'Wir identifizieren die wahrscheinliche Ursache und erläutern die Optionen.',
      'Wir reparieren, wenn sinnvoll und ehrlich; sonst empfehlen wir eine Alternative.',
    ],
    'zones_text'    => 'Wir führen Reparaturen in Benidorm, Altea, Calpe, Finestrat, La Nucía und anderen Orten der Marina Baixa durch.',
    'faq'           => [
      ['q' => 'Reparieren oder Gerät austauschen?', 'a' => 'Das hängt von Alter, Defektart und Kosten ab. Wir inspizieren zuerst und geben dann eine klare Empfehlung.'],
      ['q' => 'Kann ein tropfendes Gerät inspiziert werden?', 'a' => 'Ja. Es könnte an der Ableitung, Verschmutzung, Neigung oder dem Systembetrieb liegen.'],
      ['q' => 'Bieten Sie Service für Ferienwohnungen an?', 'a' => 'Ja, besonders wenn das Gerät schnell und zuverlässig wieder in Betrieb sein muss.'],
    ],
    'cta_event'     => 'cta_quote_service_repair_detail',
    'service_type'  => 'Klimaanlage reparieren',
  ],
  '/de/dienstleistungen/waermepumpe-aerothermie/' => [
    'slug'          => 'waermepumpe-aerothermie',
    'path'          => '/de/dienstleistungen/waermepumpe-aerothermie/',
    'breadcrumb'    => 'Wärmepumpe &amp; Aerothermie',
    'title'         => 'Wärmepumpe und Aerothermie in Benidorm und Marina Baixa | +QUECLIMA',
    'description'   => 'Wärmepumpen- und Aerothermie-Systeme in Benidorm und der Marina Baixa für effiziente Heizung, ganzjährige Klimatisierung und Energieverbesserungsprojekte.',
    'h1'            => 'Wärmepumpe und Aerothermie in Benidorm und der Marina Baixa',
    'subtitle'      => 'Wir prüfen Wärmepumpen- und Aerothermie-Lösungen, wenn sie wirklich zum Objekt, zur Nutzung und zum Sparziel passen.',
    'hero_image'    => '/assets/img/services/service-aerotermia-bomba-calor.webp',
    'hero_alt'      => 'Wärmepumpe und Aerothermie für ein Wohnhaus',
    'visual_slot'   => 'servicio-aerotermia-hero',
    'image_position'=> 'left center',
    'support_image' => [
      'src'     => '/assets/img/services/service-detail-aerotermia-bomba-calor.png',
      'alt'     => 'Wärmepumpen-Installation im Wohnhaus',
      'caption' => '',
    ],
    'intro_title'   => 'Effizienz – aber erst nach sorgfältiger Prüfung',
    'intro'         => 'Eine Wärmepumpe kann eine ausgezeichnete Lösung für Heizung, Kühlung und Energieverbesserung sein, aber jede Situation ist anders. Wir prüfen das Objekt, die Dämmung, die Nutzungsweise, vorhandene Wärmeabgabesysteme und Erwartungen, bevor wir eine Option empfehlen.',
    'bullets_title' => 'Was wir bewerten',
    'bullets'       => [
      'Objekttyp, Dämmung und zu klimatisierende Fläche.',
      'Tatsächliche Nutzung in Winter, Sommer und Zwischensaison.',
      'Kompatibilität mit bestehenden Systemen oder geplanten Erweiterungen.',
      'Platzbedarf für Geräte und Wartungsanforderungen.',
      'Komfortziele, Energieverbrauch und realistisches Budget.',
    ],
    'when_title'    => 'Wann es sinnvoll sein kann',
    'when_items'    => [
      'In Einfamilienhäusern, die Komfort und Energiekosten verbessern wollen.',
      'Bei Planung einer energetischen Sanierung oder Systemwechsels.',
      'Um ein effizientes Gerät für Kühlung und Heizung zu nutzen.',
      'Wenn Zeit ist, die Installation sorgfältig zu prüfen – statt einfach ein Gerät zu ersetzen.',
    ],
    'process_title' => 'Wie wir arbeiten',
    'process_items' => [
      'Wir prüfen Ihren Bedarf, das Objekt und das bestehende System.',
      'Wir erklären, ob eine Wärmepumpe passt oder eine einfachere Alternative besser ist.',
      'Wir erstellen einen Vorschlag nach Komfort-, Energie- und Wartungskriterien.',
    ],
    'zones_text'    => 'Wir bewerten Wärmepumpen- und Aerothermie-Lösungen in Benidorm, Altea, Calpe, Finestrat, La Nucía und an der nördlichen Costa Blanca.',
    'faq'           => [
      ['q' => 'Lohnt sich Aerothermie immer?', 'a' => 'Nicht immer. Objekt, Nutzung, bestehende Anlage und Budget müssen erst bewertet werden.'],
      ['q' => 'Funktioniert eine Wärmepumpe auch zum Heizen im Winter?', 'a' => 'Ja, sie kann eine effiziente Heizlösung sein, wenn sie richtig ausgelegt und zum Objekt passend ist.'],
      ['q' => 'Lässt sie sich mit anderen Verbesserungen kombinieren?', 'a' => 'Ja. Manchmal ist es sinnvoll, auch Dämmung, Regelung, Wärmeabgabe oder Energieergänzungssysteme zu berücksichtigen.'],
    ],
    'cta_event'     => 'cta_quote_service_heatpump_detail',
    'service_type'  => 'Wärmepumpe und Aerothermie',
  ],
  '/de/dienstleistungen/solarthermie/' => [
    'slug'          => 'solarthermie',
    'path'          => '/de/dienstleistungen/solarthermie/',
    'breadcrumb'    => 'Solarthermie',
    'title'         => 'Solarthermie in Benidorm und Marina Baixa | +QUECLIMA',
    'description'   => 'Solarthermie in Benidorm und der Marina Baixa für Warmwasser und Energieunterstützung in Wohnhäusern und Gewerbebetrieben.',
    'h1'            => 'Solarthermie in Benidorm und der Marina Baixa',
    'subtitle'      => 'Wir prüfen Solarthermieanlagen für Warmwasser und Energieunterstützung, wenn Verbrauch und verfügbare Fläche es rechtfertigen.',
    'hero_image'    => '/assets/img/services/service-energia-solar-termica.webp',
    'hero_alt'      => 'Solarthermie für Warmwasser',
    'visual_slot'   => 'servicio-solar-termica-hero',
    'image_position'=> 'right center',
    'support_image' => [
      'src'     => '/assets/img/services/service-detail-energia-solar-termica.png',
      'alt'     => 'Solarthermiepaneele auf einem Dach',
      'caption' => '',
    ],
    'intro_title'   => 'Solarunterstützung für Warmwasser',
    'intro'         => 'Solarthermie kann einen Teil des Warmwasserbedarfs in Wohnhäusern, kleinen Gemeinschaftsanlagen oder Gewerbebetrieben decken. Damit es sich lohnt, prüfen wir Verbrauch, Ausrichtung, verfügbare Dachfläche, Integration und Wartungsanforderungen.',
    'bullets_title' => 'Was wir bewerten',
    'bullets'       => [
      'Ungefährer Warmwasserverbrauch und Nutzungsmuster.',
      'Ausrichtung, Verschattung und verfügbare Dachfläche.',
      'Integration mit Speicher und bestehendem System.',
      'Zugänglichkeit für Wartung und spätere Inspektionen.',
      'Balance zwischen Investition, erwarteter Ersparnis und Systemlebensdauer.',
    ],
    'when_title'    => 'Wann es eine gute Lösung sein kann',
    'when_items'    => [
      'In Häusern mit konstantem Warmwasserbedarf.',
      'In Betrieben oder Unterkünften mit regelmäßigem Warmwasserbedarf.',
      'Bei guter Ausrichtung und ausreichend verfügbarer Dachfläche.',
      'Wenn Energieunterstützung ohne unrealistische Sparversprechen gesucht wird.',
    ],
    'process_title' => 'Wie wir arbeiten',
    'process_items' => [
      'Wir prüfen Verbrauch, Standort und das bestehende System.',
      'Wir bewerten, ob Solarthermie passt oder eine andere Option besser ist.',
      'Wir schlagen eine wartungsfreundliche Lösung entsprechend dem tatsächlichen Bedarf vor.',
    ],
    'zones_text'    => 'Wir führen Solarthermie-Projekte in Benidorm, Altea, Calpe, Finestrat, La Nucía und der Provinz Alicante durch.',
    'faq'           => [
      ['q' => 'Erzeugt Solarthermie Strom?', 'a' => 'Nein. Solarthermie dient der Warmwassererzeugung oder -unterstützung. Für Stromerzeugung werden andere Lösungen geprüft.'],
      ['q' => 'Ist Wartung erforderlich?', 'a' => 'Ja. Wie jede Anlage sollte das System periodisch geprüft werden, um Leistung und Sicherheit zu erhalten.'],
      ['q' => 'Ist sie für jedes Objekt geeignet?', 'a' => 'Nicht immer. Es hängt von Verbrauch, Ausrichtung, Verschattung, verfügbarer Fläche und Kompatibilität mit dem bestehenden System ab.'],
    ],
    'cta_event'     => 'cta_quote_service_solar_detail',
    'service_type'  => 'Solarthermie',
  ],
];
// old format removed (split, multisplit, conductos)', 'summary' => 'Proyecto llave en mano con estudio térmico, marcas líderes y garantía 3 años.', 'sections' => [['h' => 'Qué incluye', 'p' => 'Visita técnica, cálculo de carga térmica, propuesta de equipos, instalación certificada RITE, evacuación de condensados, pruebas y puesta en marcha.'], ['h' => 'Plazos y precios orientativos', 'p' => 'Pisos de 1‑3 estancias: 24–48 h. Conductos: 48–72 h. Desde 750 € + equipo (split) / desde 2.400 € (conductos).'], ['h' => 'Por qué +QUECLIMA', 'p' => 'Técnicos con amplia experiencia, acabados limpios, mínimo ruido, eficiencia y seguridad.']], 'faq' => [['q' => '¿Cuánta potencia necesito?', 'a' => 'Depende del espacio y orientación. Regla general: ~100 frigorías por m²; validamos con estudio térmico.'], ['q' => '¿Qué marcas trabajáis?', 'a' => 'Daikin, Mitsubishi Electric, Fujitsu, Panasonic, LG, Gree, Toshiba, Haier.']]], ['slug' => 'mantenimiento-climatizacion', 'title' => 'Mantenimiento de climatización (preventivo y correctivo)', 'summary' => 'Planes de mantenimiento para alargar la vida útil, reducir consumo y evitar averías.', 'sections' => [['h' => 'Tareas clave', 'p' => 'Limpieza de filtros, revisión de presiones, comprobación de fugas, drenajes y conexiones eléctricas.'], ['h' => 'Beneficios', 'p' => 'Menos consumo, mejor rendimiento y mayor confort, con alertas tempranas.']], 'faq' => [['q' => '¿Cada cuánto hacer mantenimiento?', 'a' => 'Doméstico: 1–2 veces al año. Comercial: trimestral o semestral según uso.']]], ['slug' => 'reparacion-averias', 'title' => 'Reparación de averías de aire acondicionado', 'summary' => 'Diagnóstico experto y reparación rápida. Servicio urgente 24/7.', 'sections' => [['h' => 'Síntomas comunes', 'p' => 'No enfría, hace ruido, fuga de agua, error en display, malos olores.'], ['h' => 'Proceso', 'p' => 'Diagnóstico en 24h, presupuesto cerrado y reparación con garantía.']], 'faq' => [['q' => '¿Merece la pena reparar o cambiar?', 'a' => 'Si el equipo supera 10–12 años o la reparación es costosa, evaluamos reemplazo eficiente.']]], ['slug' => 'calefaccion-bomba-de-calor', 'title' => 'Calefacción por bomba de calor y aerotermia', 'summary' => 'Sistemas eficientes para invierno con SCOP alto y control inteligente.', 'sections' => [['h' => 'Opciones', 'p' => 'Splits con modo calor, bombas de calor aire‑agua para radiadores o suelo radiante.'], ['h' => 'Ahorro', 'p' => 'La aerotermia puede reducir hasta un 30–50% el gasto frente a resistencias eléctricas.']], 'faq' => [['q' => '¿Sirve para ACS?', 'a' => 'Sí, con depósito acumulador y control adecuado.']]], ['slug' => 'instalaciones-electricas', 'title' => 'Instalaciones eléctricas y boletines', 'summary' => 'Reformas eléctricas seguras, cuadros, líneas y legalizaciones.', 'sections' => [['h' => 'Trabajos habituales', 'p' => 'Nuevas líneas, protecciones, iluminación, boletines y puesta a tierra.']], 'faq' => []], ['slug' => 'fontaneria', 'title' => 'Servicios de fontanería', 'summary' => 'Instalaciones y reparaciones de fontanería vinculadas a climatización y ACS.', 'sections' => [['h' => 'Actuaciones típicas', 'p' => 'Tomas de agua para equipos, drenajes, válvulas de seguridad, fugas.']], 'faq' => []]];
