<?php
declare(strict_types=1);

return [
  '/en/services/air-conditioning-installation/' => [
    'slug'          => 'air-conditioning-installation',
    'path'          => '/en/services/air-conditioning-installation/',
    'breadcrumb'    => 'Air conditioning installation',
    'title'         => 'Air conditioning installation in Benidorm and Marina Baixa | +QUECLIMA',
    'description'   => 'Air conditioning installation in Benidorm and the Marina Baixa for homes, holiday apartments and businesses. Site visit included and clear quote.',
    'h1'            => 'Air conditioning installation in Benidorm and Marina Baixa',
    'subtitle'      => 'We install split, multi-split and ducted systems with a site visit, power calculation and careful commissioning.',
    'hero_image'    => '/assets/img/services/service-instalacion-aire-acondicionado.webp',
    'hero_alt'      => 'Air conditioning installation in a home or commercial property',
    'visual_slot'   => 'servicio-instalacion-hero',
    'image_position'=> 'right center',
    'support_image' => [
      'src'     => '/assets/img/services/service-detail-instalacion-aire-acondicionado.png',
      'alt'     => 'Air conditioning installation with split unit and outdoor condenser',
      'caption' => '',
    ],
    'intro_title'   => 'An installation designed around real use',
    'intro'         => 'Before recommending any unit we assess the property: floor area, orientation, insulation, intended use, outdoor unit position, drainage routes and potential noise issues. The aim is to install a system that cools effectively, uses only the power it needs and is comfortable day to day.',
    'bullets_title' => 'What we take into account',
    'bullets'       => [
      'Appropriate capacity for the room, use and orientation.',
      'Indoor and outdoor unit positions for optimal performance.',
      'Pipe routing, drainage and clean finishes.',
      'Noise level, energy consumption and ease of maintenance.',
      'Commissioning, usage guidance and warranty.',
    ],
    'when_title'    => 'When to install or upgrade',
    'when_items'    => [
      'When a property does not reach a comfortable temperature in summer.',
      'If the current unit consumes too much or fails frequently.',
      'In holiday apartments where reliability, controllability and low noise matter.',
      'When preparing a commercial space for continuous use during peak season.',
    ],
    'process_title' => 'How we work',
    'process_items' => [
      'We listen to your needs and assess the location.',
      'We calculate a realistic solution without over-specifying the unit.',
      'We install with care, test the system and explain how to use it.',
    ],
    'zones_text'    => 'We carry out installations in Benidorm, Altea, Calpe, Finestrat, La Nucía and other towns in the Marina Baixa.',
    'faq'           => [
      ['q' => 'Which system is best: split, multi-split or ducted?', 'a' => 'It depends on the property, the rooms you want to cool and whether pre-installation exists. We review this before quoting.'],
      ['q' => 'Can it be installed in holiday apartments?', 'a' => 'Yes. In these cases we pay particular attention to noise, energy use, ease of operation and reliability during peak season.'],
      ['q' => 'Is a site visit necessary?', 'a' => 'It is recommended when there are questions about capacity, unit position, drainage or pipe routing.'],
    ],
    'cta_event'     => 'cta_quote_service_install_detail',
    'service_type'  => 'Air conditioning installation',
  ],
  '/en/services/climate-control-maintenance/' => [
    'slug'          => 'climate-control-maintenance',
    'path'          => '/en/services/climate-control-maintenance/',
    'breadcrumb'    => 'Climate control maintenance',
    'title'         => 'Air conditioning maintenance in Benidorm and Marina Baixa | +QUECLIMA',
    'description'   => 'Air conditioning maintenance in Benidorm and the Marina Baixa: filter cleaning, unit inspection, drainage check and preparation for the summer season.',
    'h1'            => 'Air conditioning maintenance in Benidorm and Marina Baixa',
    'subtitle'      => 'We service air conditioning units to reduce breakdowns, improve performance and get your system ready before the summer.',
    'hero_image'    => '/assets/img/services/service-mantenimiento-climatizacion.webp',
    'hero_alt'      => 'Air conditioning maintenance and unit inspection',
    'visual_slot'   => 'servicio-mantenimiento-hero',
    'image_position'=> 'right center',
    'support_image' => [
      'src'     => '/assets/img/services/service-detail-mantenimiento-climatizacion.png',
      'alt'     => 'Air conditioning maintenance and service inspection',
      'caption' => '',
    ],
    'intro_title'   => 'Maintenance to extend the unit\'s life',
    'intro'         => 'A dirty or poorly serviced unit may cool less effectively, consume more energy and fail exactly when you need it most. In homes, holiday apartments, communities and businesses we check the most common failure points and let you know clearly whether it needs cleaning, adjustment or repair.',
    'bullets_title' => 'What we inspect',
    'bullets'       => [
      'Filter cleaning and general condition check.',
      'Coil inspection, drainage and possible blockages.',
      'Visual check of outdoor units and ventilation.',
      'Noises, vibrations, odours or water leaks.',
      'Usage recommendations to reduce consumption and wear.',
    ],
    'when_title'    => 'When to book a service',
    'when_items'    => [
      'Before the hot season, especially in properties with heavy use.',
      'If the unit cools less than before or takes too long.',
      'When there are odours, drips, noise or vibrations.',
      'In holiday apartments and businesses with many operating cycles.',
    ],
    'process_title' => 'How we work',
    'process_items' => [
      'We inspect the unit and note any symptoms you have observed.',
      'We clean and check the critical accessible points.',
      'We tell you whether the system is in order or whether a repair is advisable.',
    ],
    'zones_text'    => 'We carry out maintenance in Benidorm, Altea, Calpe, Finestrat, La Nucía and nearby towns.',
    'faq'           => [
      ['q' => 'How often should maintenance be done?', 'a' => 'It depends on use. In homes one periodic service may suffice; in holiday apartments and businesses, servicing before each season is usually advisable.'],
      ['q' => 'Does maintenance prevent all breakdowns?', 'a' => 'It cannot guarantee that, but it helps detect problems early and reduces failures caused by dirt, drainage issues or lack of servicing.'],
      ['q' => 'Do you also service outdoor units?', 'a' => 'Yes, whenever they are accessible and safe to work on.'],
    ],
    'cta_event'     => 'cta_quote_service_maintenance_detail',
    'service_type'  => 'Air conditioning maintenance',
  ],
  '/en/services/air-conditioning-repair/' => [
    'slug'          => 'air-conditioning-repair',
    'path'          => '/en/services/air-conditioning-repair/',
    'breadcrumb'    => 'Air conditioning repair',
    'title'         => 'Air conditioning repair in Benidorm and Marina Baixa | +QUECLIMA',
    'description'   => 'Air conditioning repair in Benidorm and the Marina Baixa: units that do not cool, leak water, make noise or display error codes.',
    'h1'            => 'Air conditioning repair in Benidorm and Marina Baixa',
    'subtitle'      => 'We diagnose air conditioning faults before replacing parts or recommending a new unit.',
    'hero_image'    => '/assets/img/services/service-reparacion-aire-acondicionado.webp',
    'hero_alt'      => 'Air conditioning repair and diagnosis',
    'visual_slot'   => 'servicio-reparacion-hero',
    'image_position'=> 'right center',
    'support_image' => [
      'src'     => '/assets/img/services/service-detail-reparacion-aire-acondicionado.png',
      'alt'     => 'Air conditioning diagnosis and repair',
      'caption' => '',
    ],
    'intro_title'   => 'Clear diagnosis before any repair',
    'intro'         => 'When a unit stops cooling, leaks water, makes noise or shows an error code, replacement is not always necessary. We identify the root cause and explain honestly whether it makes sense to repair, adjust the system or consider a replacement.',
    'bullets_title' => 'Common faults',
    'bullets'       => [
      'Unit not cooling or taking too long to reach temperature.',
      'Drips, water leaks or drainage problems.',
      'Noises, vibrations or irregular operation.',
      'Display error codes or unexpected shutdowns.',
      'Poor performance due to dirt, wear or an improvable installation.',
    ],
    'when_title'    => 'When to request an inspection',
    'when_items'    => [
      'Before buying a new unit if you are not sure where the fault lies.',
      'When the air comes out warm or the unit runs without stopping.',
      'If water appears on the wall, floor or indoor unit drip tray.',
      'When noise or vibrations have changed compared to normal operation.',
    ],
    'process_title' => 'How we work',
    'process_items' => [
      'We note the symptoms and inspect the unit.',
      'We identify the probable cause and explain the options.',
      'We repair if it is viable and honest; if not, we recommend an alternative.',
    ],
    'zones_text'    => 'We carry out repairs in Benidorm, Altea, Calpe, Finestrat, La Nucía and other towns in the Marina Baixa.',
    'faq'           => [
      ['q' => 'Is it worth repairing or replacing the unit?', 'a' => 'It depends on age, fault type and cost. We inspect first and then give you a clear recommendation.'],
      ['q' => 'Can you inspect units that are leaking water?', 'a' => 'Yes. It may be related to drainage, dirt, tilt or system operation.'],
      ['q' => 'Do you service holiday apartments?', 'a' => 'Yes, especially when the unit needs a fast and reliable solution to remain in service.'],
    ],
    'cta_event'     => 'cta_quote_service_repair_detail',
    'service_type'  => 'Air conditioning repair',
  ],
  '/en/services/heat-pump-aerothermal/' => [
    'slug'          => 'heat-pump-aerothermal',
    'path'          => '/en/services/heat-pump-aerothermal/',
    'breadcrumb'    => 'Heat pump &amp; aerothermal',
    'title'         => 'Heat pump and aerothermal systems in Benidorm and Marina Baixa | +QUECLIMA',
    'description'   => 'Heat pump and aerothermal systems in Benidorm and the Marina Baixa for efficient heating, year-round climate control and energy improvement projects.',
    'h1'            => 'Heat pump and aerothermal systems in Benidorm and Marina Baixa',
    'subtitle'      => 'We study heat pump and aerothermal solutions when they genuinely suit the property, usage and savings target.',
    'hero_image'    => '/assets/img/services/service-aerotermia-bomba-calor.webp',
    'hero_alt'      => 'Heat pump and aerothermal system for a residential property',
    'visual_slot'   => 'servicio-aerotermia-hero',
    'image_position'=> 'left center',
    'support_image' => [
      'src'     => '/assets/img/services/service-detail-aerotermia-bomba-calor.png',
      'alt'     => 'Heat pump and aerothermal installation in a home',
      'caption' => '',
    ],
    'intro_title'   => 'Efficiency, but with a proper assessment first',
    'intro'         => 'A heat pump can be an excellent solution for heating, cooling and energy improvement, but not every situation is the same. We review the property, insulation, usage, existing emitters and expectations before recommending any option.',
    'bullets_title' => 'What we assess',
    'bullets'       => [
      'Property type, insulation and area to be conditioned.',
      'Actual use during winter, summer and mid-season.',
      'Compatibility with existing systems or future upgrades.',
      'Space available for equipment and maintenance requirements.',
      'Comfort goals, energy consumption and realistic budget.',
    ],
    'when_title'    => 'When it may make sense',
    'when_items'    => [
      'In detached properties looking to improve comfort and energy bills.',
      'When planning an energy retrofit or system change.',
      'To benefit from an efficient unit for both cooling and heating.',
      'When there is time to assess the installation properly rather than simply replacing a machine.',
    ],
    'process_title' => 'How we work',
    'process_items' => [
      'We review your needs, the property and the current system.',
      'We explain whether a heat pump is the right fit or whether there is a simpler alternative.',
      'We prepare a proposal based on comfort, energy and maintenance criteria.',
    ],
    'zones_text'    => 'We assess heat pump and aerothermal solutions in Benidorm, Altea, Calpe, Finestrat, La Nucía and the northern Costa Blanca.',
    'faq'           => [
      ['q' => 'Is aerothermal always worth it?', 'a' => 'Not always. The property, use, existing installation and budget need to be assessed before recommending it.'],
      ['q' => 'Does a heat pump work for winter heating?', 'a' => 'Yes, it can be an efficient heating solution if it is correctly sized and suits the property.'],
      ['q' => 'Can it be combined with other improvements?', 'a' => 'Yes. In some cases it makes sense to also consider insulation, controls, emitters or energy support systems.'],
    ],
    'cta_event'     => 'cta_quote_service_heatpump_detail',
    'service_type'  => 'Heat pump and aerothermal',
  ],
  '/en/services/solar-thermal-energy/' => [
    'slug'          => 'solar-thermal-energy',
    'path'          => '/en/services/solar-thermal-energy/',
    'breadcrumb'    => 'Solar thermal energy',
    'title'         => 'Solar thermal energy in Benidorm and Marina Baixa | +QUECLIMA',
    'description'   => 'Solar thermal systems in Benidorm and the Marina Baixa for domestic hot water and energy support in homes and businesses.',
    'h1'            => 'Solar thermal energy in Benidorm and Marina Baixa',
    'subtitle'      => 'We assess solar thermal installations for hot water and energy support when consumption and available space justify it.',
    'hero_image'    => '/assets/img/services/service-energia-solar-termica.webp',
    'hero_alt'      => 'Solar thermal energy for domestic hot water',
    'visual_slot'   => 'servicio-solar-termica-hero',
    'image_position'=> 'right center',
    'support_image' => [
      'src'     => '/assets/img/services/service-detail-energia-solar-termica.png',
      'alt'     => 'Solar thermal panels on a roof',
      'caption' => '',
    ],
    'intro_title'   => 'Solar support for hot water',
    'intro'         => 'Solar thermal can help cover part of the hot water demand in homes, small communities or businesses. For it to make sense we need to review consumption, orientation, available space, integration and maintenance requirements.',
    'bullets_title' => 'What we assess',
    'bullets'       => [
      'Approximate hot water consumption and usage patterns.',
      'Orientation, shading and available roof space for collectors.',
      'Integration with storage and the existing system.',
      'Accessibility for maintenance and future inspections.',
      'Balance between investment, expected savings and system lifespan.',
    ],
    'when_title'    => 'When it may be a good fit',
    'when_items'    => [
      'In homes with stable hot water consumption.',
      'In businesses or accommodation with regular hot water demand.',
      'When there is good orientation and available space.',
      'When looking for energy support without unrealistic savings promises.',
    ],
    'process_title' => 'How we work',
    'process_items' => [
      'We review consumption, location and the current system.',
      'We assess whether solar thermal is a good fit or whether another option is better.',
      'We propose a maintainable solution matched to actual use.',
    ],
    'zones_text'    => 'We carry out solar thermal projects in Benidorm, Altea, Calpe, Finestrat, La Nucía and Alicante province.',
    'faq'           => [
      ['q' => 'Does solar thermal generate electricity?', 'a' => 'No. Solar thermal is focused on producing or supporting hot water. For electricity generation, other solutions are studied.'],
      ['q' => 'Does it need maintenance?', 'a' => 'Yes. Like any installation, the system and its components should be inspected periodically to maintain performance and safety.'],
      ['q' => 'Is it suitable for any property?', 'a' => 'Not always. It depends on consumption, orientation, shading, available space and compatibility with the existing system.'],
    ],
    'cta_event'     => 'cta_quote_service_solar_detail',
    'service_type'  => 'Solar thermal energy',
  ],
];
