<?php
declare(strict_types=1);

return [
  '/es/servicios/instalacion-aire-acondicionado/' => [
    'slug' => 'instalacion-aire-acondicionado',
    'path' => '/es/servicios/instalacion-aire-acondicionado/',
    'breadcrumb' => 'Instalaci&oacute;n de aire acondicionado',
    'title' => 'Instalaci&oacute;n de aire acondicionado en Benidorm y Marina Baixa | +QUECLIMA',
    'description' => 'Instalaci&oacute;n de aire acondicionado en Benidorm y Marina Baixa para viviendas, apartamentos tur&iacute;sticos y locales. Visita previa y presupuesto claro.',
    'h1' => 'Instalaci&oacute;n de aire acondicionado en Benidorm y Marina Baixa',
    'subtitle' => 'Instalamos equipos split, multisplit y conductos con visita previa, c&aacute;lculo de potencia y una puesta en marcha cuidada.',
    'hero_image' => '/assets/img/services/service-instalacion-aire-acondicionado.webp',
    'hero_alt' => 'Instalaci&oacute;n de aire acondicionado en vivienda o local',
    'visual_slot' => 'servicio-instalacion-hero',
    'image_position' => 'right center',
    'support_image' => [
      'src' => '/assets/img/services/module-instalacion.webp',
      'alt' => 'Instalaci&oacute;n de aire acondicionado split',
      'caption' => '',
    ],
    'intro_title' => 'Una instalaci&oacute;n pensada para el uso real',
    'intro' => 'Antes de recomendar un equipo revisamos la vivienda o el local: metros, orientaci&oacute;n, aislamiento, uso previsto, ubicaci&oacute;n de la unidad exterior, desag&uuml;es y posibles molestias por ruido. La idea es instalar un sistema que enfr&iacute;e bien, consuma lo justo y sea c&oacute;modo en el d&iacute;a a d&iacute;a.',
    'bullets_title' => 'Qu&eacute; tenemos en cuenta',
    'bullets' => [
      'Potencia adecuada seg&uacute;n estancia, uso y orientaci&oacute;n.',
      'Ubicaci&oacute;n de unidad interior y exterior para trabajar con buen rendimiento.',
      'Recorrido de tuber&iacute;as, drenajes y acabados limpios.',
      'Nivel sonoro, consumo y facilidad de mantenimiento.',
      'Puesta en marcha, explicaci&oacute;n de uso y garant&iacute;a del trabajo.',
    ],
    'when_title' => 'Cu&aacute;ndo conviene instalar o renovar',
    'when_items' => [
      'Cuando una vivienda no alcanza una temperatura confortable en verano.',
      'Si el equipo actual consume demasiado o se aver&iacute;a con frecuencia.',
      'En apartamentos tur&iacute;sticos donde interesa fiabilidad, control y bajo ruido.',
      'Al preparar un local o negocio para uso continuado en temporada alta.',
    ],
    'process_title' => 'C&oacute;mo trabajamos',
    'process_items' => [
      'Escuchamos qu&eacute; necesitas y revisamos la ubicaci&oacute;n.',
      'Calculamos una soluci&oacute;n realista, sin sobredimensionar el equipo.',
      'Instalamos con cuidado, probamos el sistema y dejamos explicado el uso.',
    ],
    'zones_text' => 'Realizamos instalaciones en Benidorm, Altea, Calpe, Finestrat, La Nuc&iacute;a y otras localidades de la Marina Baixa.',
    'faq' => [
      ['q' => 'Qu&eacute; sistema conviene m&aacute;s: split, multisplit o conductos?', 'a' => 'Depende de la vivienda, las estancias que quieras climatizar y si existe preinstalaci&oacute;n. Lo revisamos antes de presupuestar.'],
      ['q' => 'Se puede instalar en apartamentos tur&iacute;sticos?', 'a' => 'S&iacute;. En estos casos cuidamos especialmente el ruido, el consumo, la facilidad de uso y la fiabilidad en temporada alta.'],
      ['q' => 'Hace falta visita previa?', 'a' => 'Es lo recomendable cuando hay dudas de potencia, ubicaci&oacute;n, drenajes o recorrido de instalaci&oacute;n.'],
    ],
    'cta_event' => 'cta_quote_service_install_detail',
    'service_type' => 'Instalaci&oacute;n de aire acondicionado',
  ],
  '/es/servicios/mantenimiento-climatizacion/' => [
    'slug' => 'mantenimiento-climatizacion',
    'path' => '/es/servicios/mantenimiento-climatizacion/',
    'breadcrumb' => 'Mantenimiento de climatizaci&oacute;n',
    'title' => 'Mantenimiento de climatizaci&oacute;n en Benidorm y Marina Baixa | +QUECLIMA',
    'description' => 'Mantenimiento de climatizaci&oacute;n en Benidorm y Marina Baixa: limpieza, revisi&oacute;n de equipos, desag&uuml;es, unidades exteriores y preparaci&oacute;n para verano.',
    'h1' => 'Mantenimiento de climatizaci&oacute;n en Benidorm y Marina Baixa',
    'subtitle' => 'Revisamos equipos de climatizaci&oacute;n para reducir aver&iacute;as, mejorar el rendimiento y llegar al verano con el sistema preparado.',
    'hero_image' => '/assets/img/services/service-mantenimiento-climatizacion.webp',
    'hero_alt' => 'Mantenimiento de climatizaci&oacute;n y revisi&oacute;n de equipos',
    'visual_slot' => 'servicio-mantenimiento-hero',
    'image_position' => 'right center',
    'support_image' => [
      'src' => '/assets/img/services/module-mantenimiento.webp',
      'alt' => 'Mantenimiento y limpieza de aire acondicionado',
      'caption' => '',
    ],
    'intro_title' => 'Mantenimiento para alargar la vida del equipo',
    'intro' => 'Un equipo sucio o mal revisado puede enfriar peor, consumir m&aacute;s y fallar justo cuando m&aacute;s se necesita. En viviendas, apartamentos tur&iacute;sticos, comunidades y negocios revisamos los puntos habituales de fallo y dejamos claro si conviene limpiar, ajustar o reparar.',
    'bullets_title' => 'Qu&eacute; revisamos',
    'bullets' => [
      'Limpieza de filtros y comprobaci&oacute;n del estado general.',
      'Revisi&oacute;n de bater&iacute;as, desag&uuml;es y posibles obstrucciones.',
      'Comprobaci&oacute;n visual de unidades exteriores y ventilaci&oacute;n.',
      'Ruidos, vibraciones, olores o p&eacute;rdidas de agua.',
      'Recomendaciones de uso para reducir consumo y desgaste.',
    ],
    'when_title' => 'Cu&aacute;ndo pedir mantenimiento',
    'when_items' => [
      'Antes de la temporada de calor, especialmente en viviendas de uso intensivo.',
      'Si el equipo enfr&iacute;a menos que antes o tarda demasiado.',
      'Cuando hay olores, goteos, ruido o vibraciones.',
      'En apartamentos tur&iacute;sticos y negocios con muchos ciclos de uso.',
    ],
    'process_title' => 'C&oacute;mo trabajamos',
    'process_items' => [
      'Revisamos el equipo y los s&iacute;ntomas que hayas notado.',
      'Limpiamos y comprobamos los puntos cr&iacute;ticos accesibles.',
      'Te indicamos si el sistema est&aacute; correcto o si conviene una reparaci&oacute;n.',
    ],
    'zones_text' => 'Prestamos mantenimiento en Benidorm, Altea, Calpe, Finestrat, La Nuc&iacute;a y localidades cercanas.',
    'faq' => [
      ['q' => 'Cada cu&aacute;nto conviene hacer mantenimiento?', 'a' => 'Depende del uso. En viviendas puede bastar una revisi&oacute;n peri&oacute;dica; en apartamentos tur&iacute;sticos y negocios suele convenir revisar antes de temporada.'],
      ['q' => 'El mantenimiento evita todas las aver&iacute;as?', 'a' => 'No puede garantizarlo, pero ayuda a detectar problemas pronto y reduce fallos por suciedad, desag&uuml;es o falta de revisi&oacute;n.'],
      ['q' => 'Tambi&eacute;n revis&aacute;is unidades exteriores?', 'a' => 'S&iacute;, siempre que sean accesibles y sea seguro hacerlo.'],
    ],
    'cta_event' => 'cta_quote_service_maintenance_detail',
    'service_type' => 'Mantenimiento de climatizaci&oacute;n',
  ],
  '/es/servicios/reparacion-aire-acondicionado/' => [
    'slug' => 'reparacion-aire-acondicionado',
    'path' => '/es/servicios/reparacion-aire-acondicionado/',
    'breadcrumb' => 'Reparaci&oacute;n de aire acondicionado',
    'title' => 'Reparaci&oacute;n de aire acondicionado en Benidorm y Marina Baixa | +QUECLIMA',
    'description' => 'Reparaci&oacute;n de aire acondicionado en Benidorm y Marina Baixa: equipos que no enfr&iacute;an, pierden agua, hacen ruido o muestran errores.',
    'h1' => 'Reparaci&oacute;n de aire acondicionado en Benidorm y Marina Baixa',
    'subtitle' => 'Diagnosticamos aver&iacute;as de aire acondicionado antes de cambiar piezas o recomendar un equipo nuevo.',
    'hero_image' => '/assets/img/services/service-reparacion-aire-acondicionado.webp',
    'hero_alt' => 'Reparaci&oacute;n y diagn&oacute;stico de aire acondicionado',
    'visual_slot' => 'servicio-reparacion-hero',
    'image_position' => 'right center',
    'support_image' => [
      'src' => '/assets/img/services/module-reparacion.webp',
      'alt' => 'Diagn&oacute;stico de aver&iacute;a en aire acondicionado',
      'caption' => '',
    ],
    'intro_title' => 'Diagn&oacute;stico claro antes de reparar',
    'intro' => 'Cuando un equipo no enfr&iacute;a, pierde agua, hace ruido o marca un error, no siempre hace falta sustituirlo. Revisamos el origen del problema y explicamos si compensa reparar, ajustar el sistema o valorar una renovaci&oacute;n.',
    'bullets_title' => 'Aver&iacute;as habituales',
    'bullets' => [
      'El equipo no enfr&iacute;a o tarda mucho en alcanzar temperatura.',
      'Goteos, p&eacute;rdidas de agua o problemas de desag&uuml;e.',
      'Ruidos, vibraciones o funcionamiento irregular.',
      'Errores en pantalla o apagados inesperados.',
      'Bajo rendimiento por suciedad, desgaste o instalaci&oacute;n mejorable.',
    ],
    'when_title' => 'Cu&aacute;ndo pedir revisi&oacute;n',
    'when_items' => [
      'Antes de comprar otro equipo si no tienes claro el origen del fallo.',
      'Cuando el aire sale templado o el equipo trabaja sin descanso.',
      'Si aparece agua en pared, suelo o bandeja de la unidad interior.',
      'Cuando el ruido o las vibraciones han cambiado respecto al uso normal.',
    ],
    'process_title' => 'C&oacute;mo trabajamos',
    'process_items' => [
      'Recogemos los s&iacute;ntomas y revisamos el equipo.',
      'Identificamos la causa probable y explicamos opciones.',
      'Reparamos si es viable y honesto; si no, recomendamos alternativa.',
    ],
    'zones_text' => 'Atendemos reparaciones en Benidorm, Altea, Calpe, Finestrat, La Nuc&iacute;a y otras zonas de la Marina Baixa.',
    'faq' => [
      ['q' => 'Conviene reparar o cambiar el equipo?', 'a' => 'Depende de la antig&uuml;edad, el tipo de aver&iacute;a y el coste. Primero revisamos y despu&eacute;s te damos una recomendaci&oacute;n clara.'],
      ['q' => 'Pod&eacute;is revisar equipos que pierden agua?', 'a' => 'S&iacute;. Puede estar relacionado con desag&uuml;es, suciedad, inclinaci&oacute;n o funcionamiento del sistema.'],
      ['q' => 'Atend&eacute;is apartamentos tur&iacute;sticos?', 'a' => 'S&iacute;, especialmente cuando el equipo necesita una soluci&oacute;n r&aacute;pida y fiable para seguir dando servicio.'],
    ],
    'cta_event' => 'cta_quote_service_repair_detail',
    'service_type' => 'Reparaci&oacute;n de aire acondicionado',
  ],
  '/es/servicios/aerotermia-bomba-calor/' => [
    'slug' => 'aerotermia-bomba-calor',
    'path' => '/es/servicios/aerotermia-bomba-calor/',
    'breadcrumb' => 'Aerotermia y bomba de calor',
    'title' => 'Aerotermia y bomba de calor en Benidorm y Marina Baixa | +QUECLIMA',
    'description' => 'Aerotermia y bomba de calor en Benidorm y Marina Baixa para calefacci&oacute;n eficiente, climatizaci&oacute;n y proyectos energ&eacute;ticos con estudio previo.',
    'h1' => 'Aerotermia y bomba de calor en Benidorm y Marina Baixa',
    'subtitle' => 'Estudiamos soluciones de bomba de calor y aerotermia cuando encajan con la vivienda, el uso y el objetivo de ahorro.',
    'hero_image' => '/assets/img/services/service-aerotermia-bomba-calor.webp',
    'hero_alt' => 'Aerotermia y bomba de calor para vivienda',
    'visual_slot' => 'servicio-aerotermia-hero',
    'image_position' => 'left center',
    'support_image' => [
      'src' => '/assets/img/services/module-aerotermia.webp',
      'alt' => 'Equipo de bomba de calor y aerotermia',
      'caption' => '',
    ],
    'intro_title' => 'Eficiencia, pero con estudio previo',
    'intro' => 'La bomba de calor puede ser una buena soluci&oacute;n para calefacci&oacute;n, climatizaci&oacute;n y mejora energ&eacute;tica, pero no todos los casos son iguales. Revisamos vivienda, aislamiento, uso, emisores disponibles y expectativas antes de recomendar una opci&oacute;n.',
    'bullets_title' => 'Qu&eacute; valoramos',
    'bullets' => [
      'Tipo de vivienda, aislamiento y superficie a climatizar.',
      'Uso real durante invierno, verano y entretiempo.',
      'Compatibilidad con sistemas existentes o futuras mejoras.',
      'Espacio disponible para equipos y necesidades de mantenimiento.',
      'Objetivo de confort, consumo y presupuesto razonable.',
    ],
    'when_title' => 'Cu&aacute;ndo puede tener sentido',
    'when_items' => [
      'En viviendas unifamiliares que buscan mejorar confort y consumo.',
      'Cuando se plantea una reforma energ&eacute;tica o cambio de sistema.',
      'Si se quiere aprovechar un equipo eficiente para fr&iacute;o y calor.',
      'Cuando hay margen para estudiar bien la instalaci&oacute;n, no solo cambiar una m&aacute;quina.',
    ],
    'process_title' => 'C&oacute;mo trabajamos',
    'process_items' => [
      'Revisamos necesidades, vivienda y sistema actual.',
      'Explicamos si la bomba de calor encaja o si hay una alternativa m&aacute;s sencilla.',
      'Preparamos una propuesta con criterios de confort, consumo y mantenimiento.',
    ],
    'zones_text' => 'Estudiamos soluciones de aerotermia y bomba de calor en Benidorm, Altea, Calpe, Finestrat, La Nuc&iacute;a y Costa Blanca norte.',
    'faq' => [
      ['q' => 'La aerotermia siempre merece la pena?', 'a' => 'No siempre. Hay que estudiar vivienda, uso, instalaci&oacute;n existente y presupuesto antes de recomendarla.'],
      ['q' => 'Una bomba de calor sirve para invierno?', 'a' => 'S&iacute;, puede ser una soluci&oacute;n eficiente de calefacci&oacute;n si est&aacute; bien dimensionada y encaja con la vivienda.'],
      ['q' => 'Se puede combinar con otras mejoras?', 'a' => 'S&iacute;. En algunos casos tiene sentido estudiar tambi&eacute;n aislamiento, control, emisores o apoyo energ&eacute;tico.'],
    ],
    'cta_event' => 'cta_quote_service_heatpump_detail',
    'service_type' => 'Aerotermia y bomba de calor',
  ],
  '/es/servicios/energia-solar-termica/' => [
    'slug' => 'energia-solar-termica',
    'path' => '/es/servicios/energia-solar-termica/',
    'breadcrumb' => 'Energ&iacute;a solar t&eacute;rmica',
    'title' => 'Energ&iacute;a solar t&eacute;rmica en Benidorm y Marina Baixa | +QUECLIMA',
    'description' => 'Energ&iacute;a solar t&eacute;rmica en Benidorm y Marina Baixa para agua caliente sanitaria y apoyo energ&eacute;tico en viviendas y negocios.',
    'h1' => 'Energ&iacute;a solar t&eacute;rmica en Benidorm y Marina Baixa',
    'subtitle' => 'Valoramos instalaciones de solar t&eacute;rmica para agua caliente sanitaria y apoyo energ&eacute;tico cuando el consumo y el espacio lo justifican.',
    'hero_image' => '/assets/img/services/service-energia-solar-termica.webp',
    'hero_alt' => 'Energ&iacute;a solar t&eacute;rmica para agua caliente',
    'visual_slot' => 'servicio-solar-termica-hero',
    'image_position' => 'right center',
    'support_image' => [
      'src' => '/assets/img/services/module-solar-termica.webp',
      'alt' => 'Paneles de energ&iacute;a solar t&eacute;rmica',
      'caption' => '',
    ],
    'intro_title' => 'Apoyo solar para agua caliente',
    'intro' => 'La energ&iacute;a solar t&eacute;rmica puede ayudar a cubrir parte del consumo de agua caliente en viviendas, comunidades peque&ntilde;as o negocios. Para que tenga sentido hay que revisar consumo, orientaci&oacute;n, espacio disponible, integraci&oacute;n y mantenimiento.',
    'bullets_title' => 'Qu&eacute; estudiamos',
    'bullets' => [
      'Consumo aproximado de agua caliente y horarios de uso.',
      'Orientaci&oacute;n, sombras y espacio disponible para captadores.',
      'Integraci&oacute;n con acumulaci&oacute;n y sistema existente.',
      'Accesibilidad para mantenimiento y revisiones futuras.',
      'Equilibrio entre inversi&oacute;n, ahorro esperado y vida &uacute;til.',
    ],
    'when_title' => 'Cu&aacute;ndo puede encajar',
    'when_items' => [
      'En viviendas con consumo estable de agua caliente.',
      'En negocios o alojamientos con demanda frecuente de ACS.',
      'Cuando hay buena orientaci&oacute;n y espacio disponible.',
      'Si se busca apoyo energ&eacute;tico sin promesas exageradas de ahorro.',
    ],
    'process_title' => 'C&oacute;mo trabajamos',
    'process_items' => [
      'Revisamos consumo, ubicaci&oacute;n y sistema actual.',
      'Valoramos si la solar t&eacute;rmica encaja o si conviene otra opci&oacute;n.',
      'Planteamos una soluci&oacute;n mantenible y ajustada al uso real.',
    ],
    'zones_text' => 'Trabajamos proyectos de solar t&eacute;rmica en Benidorm, Altea, Calpe, Finestrat, La Nuc&iacute;a y provincia de Alicante.',
    'faq' => [
      ['q' => 'La solar t&eacute;rmica sirve para electricidad?', 'a' => 'No. La solar t&eacute;rmica se orienta principalmente a producir o apoyar agua caliente. Para electricidad se estudian otras soluciones.'],
      ['q' => 'Hace falta mantenimiento?', 'a' => 'S&iacute;. Como cualquier instalaci&oacute;n, conviene revisar el estado del sistema y sus componentes para mantener rendimiento y seguridad.'],
      ['q' => 'Es adecuada para cualquier vivienda?', 'a' => 'No siempre. Depende del consumo, orientaci&oacute;n, sombras, espacio disponible e integraci&oacute;n con el sistema existente.'],
    ],
    'cta_event' => 'cta_quote_service_solar_detail',
    'service_type' => 'Energ&iacute;a solar t&eacute;rmica',
  ],
];
