<?php
declare(strict_types=1);

return [
  '/nl/diensten/airco-installatie/' => [
    'slug'          => 'airco-installatie',
    'path'          => '/nl/diensten/airco-installatie/',
    'breadcrumb'    => 'Airco installeren',
    'title'         => 'Airco installeren in Benidorm en Marina Baixa | +QUECLIMA',
    'description'   => 'Airconditioning installeren in Benidorm en de Marina Baixa voor woningen, vakantieappartementen en bedrijven. Plaatsbezoek inbegrepen en duidelijke offerte.',
    'h1'            => 'Airco installeren in Benidorm en de Marina Baixa',
    'subtitle'      => 'Wij installeren split-, multi-split- en kanaalsystemen met een plaatsbezoek, vermogensberekening en zorgvuldige inbedrijfstelling.',
    'hero_image'    => '/assets/img/services/service-instalacion-aire-acondicionado.webp',
    'hero_alt'      => 'Airco installeren in een woning',
    'visual_slot'   => 'servicio-instalacion-hero',
    'image_position'=> 'right center',
    'support_image' => [
      'src'     => '/assets/img/services/service-detail-instalacion-aire-acondicionado.png',
      'alt'     => 'Airco-installatie met binnen- en buitenunit',
      'caption' => '',
    ],
    'intro_title'   => 'Een installatie afgestemd op het werkelijke gebruik',
    'intro'         => 'Voordat wij een toestel aanbevelen, beoordelen wij de woning: vloeroppervlak, orientatie, isolatie, gebruikswijze, positie van de buitenunit, condensaatafvoer en mogelijke geluidsproblemen. Het doel is een systeem dat effectief koelt, alleen het benodigde vermogen verbruikt en dagelijks comfortabel is.',
    'bullets_title' => 'Waar wij rekening mee houden',
    'bullets'       => [
      'Geschikte capaciteit voor de ruimte, het gebruik en de orientatie.',
      'Optimale positionering van binnen- en buitenunit.',
      'Leidingvoering, condensaatafvoer en nette afwerking.',
      'Geluidsniveau, energieverbruik en onderhoudsgemak.',
      'Inbedrijfstelling, gebruiksinstructie en garantie.',
    ],
    'when_title'    => 'Wanneer installeren of vervangen',
    'when_items'    => [
      'Als de woning in de zomer geen aangename temperatuur bereikt.',
      'Als het huidige toestel te veel verbruikt of regelmatig uitvalt.',
      'In vakantieappartementen waar betrouwbaarheid en laag geluid tellen.',
      'Bij bedrijfsruimten die in het hoogseizoen continu worden gebruikt.',
    ],
    'process_title' => 'Hoe wij werken',
    'process_items' => [
      'Wij luisteren naar uw wensen en beoordelen de locatie.',
      'Wij berekenen een realistische oplossing zonder overdimensionering.',
      'Wij installeren zorgvuldig, testen het systeem en leggen de bediening uit.',
    ],
    'zones_text'    => 'Wij voeren installaties uit in Benidorm, Altea, Calpe, Finestrat, La Nucia en andere plaatsen in de Marina Baixa.',
    'faq'           => [
      ['q' => 'Wat is beter: split, multi-split of kanaal?', 'a' => 'Dat hangt af van de woning, de te koelen ruimten en eventuele voorinstallaties. Wij beoordelen dit voor de offerte.'],
      ['q' => 'Kan het worden geinstalleerd in vakantieappartementen?', 'a' => 'Ja. In dat geval letten wij extra op geluid, energieverbruik, gebruiksgemak en betrouwbaarheid.'],
      ['q' => 'Is een plaatsbezoek noodzakelijk?', 'a' => 'Aanbevolen wanneer er vragen zijn over capaciteit, positie van de units of leidingvoering.'],
    ],
    'cta_event'     => 'cta_quote_service_install_detail',
    'service_type'  => 'Airco installeren',
  ],
  '/nl/diensten/klimaatbeheersing-onderhoud/' => [
    'slug'          => 'klimaatbeheersing-onderhoud',
    'path'          => '/nl/diensten/klimaatbeheersing-onderhoud/',
    'breadcrumb'    => 'Klimaatbeheersing onderhoud',
    'title'         => 'Airco-onderhoud in Benidorm en Marina Baixa | +QUECLIMA',
    'description'   => 'Airco-onderhoud in Benidorm en de Marina Baixa: filtreinigning, unitinspectie, afvoercontrole en voorbereiding voor het zomerseizoen.',
    'h1'            => 'Airco-onderhoud in Benidorm en de Marina Baixa',
    'subtitle'      => 'Wij onderhouden airconditioning-units om storingen te verminderen en het systeem klaar te maken voor de zomer.',
    'hero_image'    => '/assets/img/services/service-mantenimiento-climatizacion.webp',
    'hero_alt'      => 'Airco-onderhoud en unitinspectie',
    'visual_slot'   => 'servicio-mantenimiento-hero',
    'image_position'=> 'right center',
    'support_image' => [
      'src'     => '/assets/img/services/service-detail-mantenimiento-climatizacion.png',
      'alt'     => 'Airco-onderhoud en technische inspectie',
      'caption' => '',
    ],
    'intro_title'   => 'Onderhoud verlengt de levensduur',
    'intro'         => 'Een vuil of slecht onderhouden toestel koelt minder goed, verbruikt meer energie en valt precies op het slechtste moment uit. In woningen, vakantieappartementen en bedrijven controleren wij de meest voorkomende zwakke punten en informeren u duidelijk over reiniging, afstelling of reparatie.',
    'bullets_title' => 'Wat wij inspecteren',
    'bullets'       => [
      'Filtreininging en algemene conditiecontrole.',
      'Inspectie van warmtewisselaars, condensaatafvoer en mogelijke verstoppingen.',
      'Visuele controle van buitenunits en ventilatie.',
      'Geluiden, trillingen, geuren of waterlekken.',
      'Gebruiksaanbevelingen om verbruik en slijtage te beperken.',
    ],
    'when_title'    => 'Wanneer onderhoud plannen',
    'when_items'    => [
      'Voor het warme seizoen, vooral bij zwaar gebruikte panden.',
      'Als het toestel minder goed koelt of er langer over doet.',
      'Bij geuren, druppels, geluiden of trillingen.',
      'In vakantieappartementen en bedrijven met veel gebruikscycli.',
    ],
    'process_title' => 'Hoe wij werken',
    'process_items' => [
      'Wij inspecteren het toestel en noteren de gemelde symptomen.',
      'Wij reinigen en controleren de kritische toegankelijke punten.',
      'Wij laten weten of alles in orde is of reparatie aangeraden is.',
    ],
    'zones_text'    => 'Wij voeren onderhoud uit in Benidorm, Altea, Calpe, Finestrat, La Nucia en nabijgelegen plaatsen.',
    'faq'           => [
      ['q' => 'Hoe vaak moet onderhoud worden gedaan?', 'a' => 'Dat hangt af van het gebruik. In woningen kan een periodieke beurt volstaan; in vakantieappartementen en bedrijven is onderhoud voor elk seizoen doorgaans verstandig.'],
      ['q' => 'Voorkomt onderhoud alle storingen?', 'a' => 'Dat kan niet worden gegarandeerd, maar het helpt problemen vroeg te detecteren en storingen door vuil of gebrek aan onderhoud te verminderen.'],
      ['q' => 'Worden ook buitenunits onderhouden?', 'a' => 'Ja, wanneer ze toegankelijk en veilig bereikbaar zijn.'],
    ],
    'cta_event'     => 'cta_quote_service_maintenance_detail',
    'service_type'  => 'Airco-onderhoud',
  ],
  '/nl/diensten/airco-reparatie/' => [
    'slug'          => 'airco-reparatie',
    'path'          => '/nl/diensten/airco-reparatie/',
    'breadcrumb'    => 'Airco repareren',
    'title'         => 'Airco repareren in Benidorm en Marina Baixa | +QUECLIMA',
    'description'   => 'Airconditioning repareren in Benidorm en de Marina Baixa: koelt niet, lekt water, maakt lawaai of toont foutcodes.',
    'h1'            => 'Airco repareren in Benidorm en de Marina Baixa',
    'subtitle'      => 'Wij diagnosticeren airco-storingen voordat onderdelen worden vervangen of een nieuw toestel wordt aanbevolen.',
    'hero_image'    => '/assets/img/services/service-reparacion-aire-acondicionado.webp',
    'hero_alt'      => 'Airco repareren en diagnose',
    'visual_slot'   => 'servicio-reparacion-hero',
    'image_position'=> 'right center',
    'support_image' => [
      'src'     => '/assets/img/services/service-detail-reparacion-aire-acondicionado.png',
      'alt'     => 'Airco-diagnose en reparatie',
      'caption' => '',
    ],
    'intro_title'   => 'Duidelijke diagnose voor de reparatie',
    'intro'         => 'Als een toestel niet meer koelt, water lekt, lawaai maakt of een foutcode toont, is vervanging niet altijd noodzakelijk. Wij identificeren de werkelijke oorzaak en leggen eerlijk uit of reparatie, systeemafstelling of vervanging zinvol is.',
    'bullets_title' => 'Veelvoorkomende storingen',
    'bullets'       => [
      'Toestel koelt niet of bereikt temperatuur te langzaam.',
      'Druppels, waterlekken of afvoerproblemen.',
      'Geluiden, trillingen of onregelmatige werking.',
      'Foutcodes op display of onverwachte uitschakelingen.',
      'Slechte prestaties door vuil, slijtage of een te verbeteren installatie.',
    ],
    'when_title'    => 'Wanneer een inspectie aanvragen',
    'when_items'    => [
      'Voor de aankoop van een nieuw toestel als u de oorzaak niet kent.',
      'Als de lucht warm is of het toestel doorloopt zonder te stoppen.',
      'Bij watervlekken op de muur, vloer of in de condensatebak.',
      'Als geluid of trillingen zijn veranderd ten opzichte van normaal.',
    ],
    'process_title' => 'Hoe wij werken',
    'process_items' => [
      'Wij noteren de symptomen en inspecteren het toestel.',
      'Wij identificeren de oorzaak en leggen de opties uit.',
      'Wij repareren als het haalbaar en eerlijk is; zo niet, bevelen wij een alternatief aan.',
    ],
    'zones_text'    => 'Wij voeren reparaties uit in Benidorm, Altea, Calpe, Finestrat, La Nucia en andere plaatsen in de Marina Baixa.',
    'faq'           => [
      ['q' => 'Repareren of toestel vervangen?', 'a' => 'Dat hangt af van leeftijd, type storing en kosten. Wij inspecteren eerst en geven daarna een duidelijk advies.'],
      ['q' => 'Kunt u een lekkend toestel inspecteren?', 'a' => 'Ja. Het kan te maken hebben met de afvoer, vuil, helling of de werking van het systeem.'],
      ['q' => 'Service voor vakantieappartementen?', 'a' => 'Ja, zeker wanneer het toestel snel en betrouwbaar weer in gebruik moet zijn.'],
    ],
    'cta_event'     => 'cta_quote_service_repair_detail',
    'service_type'  => 'Airco repareren',
  ],
  '/nl/diensten/warmtepomp-aerothermie/' => [
    'slug'          => 'warmtepomp-aerothermie',
    'path'          => '/nl/diensten/warmtepomp-aerothermie/',
    'breadcrumb'    => 'Warmtepomp &amp; aerothermie',
    'title'         => 'Warmtepomp en aerothermie in Benidorm en Marina Baixa | +QUECLIMA',
    'description'   => 'Warmtepomp- en aerothermiesystemen in Benidorm en de Marina Baixa voor efficiënte verwarming, jaarrond klimaatbeheersing en energieverbeteringsprojecten.',
    'h1'            => 'Warmtepomp en aerothermie in Benidorm en de Marina Baixa',
    'subtitle'      => 'Wij beoordelen warmtepomp- en aerothermie-oplossingen wanneer ze echt passen bij de woning, het gebruik en de spaarwens.',
    'hero_image'    => '/assets/img/services/service-aerotermia-bomba-calor.webp',
    'hero_alt'      => 'Warmtepomp en aerothermie voor een woning',
    'visual_slot'   => 'servicio-aerotermia-hero',
    'image_position'=> 'left center',
    'support_image' => [
      'src'     => '/assets/img/services/service-detail-aerotermia-bomba-calor.png',
      'alt'     => 'Warmtepompinstallatie in een woning',
      'caption' => '',
    ],
    'intro_title'   => 'Efficientie, maar eerst een goede beoordeling',
    'intro'         => 'Een warmtepomp kan een uitstekende oplossing zijn voor verwarming, koeling en energieverbetering, maar elke situatie is anders. Wij beoordelen de woning, isolatie, gebruik, bestaande afgiftemiddelen en verwachtingen voordat wij een optie aanbevelen.',
    'bullets_title' => 'Wat wij beoordelen',
    'bullets'       => [
      'Type woning, isolatie en te conditioneren oppervlak.',
      'Werkelijk gebruik in winter, zomer en tussenseizoen.',
      'Compatibiliteit met bestaande systemen of toekomstige uitbreidingen.',
      'Beschikbare ruimte voor apparatuur en onderhoudseisen.',
      'Comfortdoelen, energieverbruik en realistisch budget.',
    ],
    'when_title'    => 'Wanneer het zinvol kan zijn',
    'when_items'    => [
      'In vrijstaande woningen die comfort en energiekosten willen verbeteren.',
      'Bij een energetische renovatie of systeemwisseling.',
      'Om te profiteren van een efficiente unit voor zowel koeling als verwarming.',
      'Wanneer er tijd is om de installatie goed te beoordelen.',
    ],
    'process_title' => 'Hoe wij werken',
    'process_items' => [
      'Wij beoordelen uw wensen, de woning en het huidige systeem.',
      'Wij leggen uit of een warmtepomp geschikt is of dat er een eenvoudiger alternatief is.',
      'Wij stellen een voorstel op op basis van comfort-, energie- en onderhoudscriteria.',
    ],
    'zones_text'    => 'Wij beoordelen warmtepomp-oplossingen in Benidorm, Altea, Calpe, Finestrat, La Nucia en de noordelijke Costa Blanca.',
    'faq'           => [
      ['q' => 'Is aerothermie altijd de moeite waard?', 'a' => 'Niet altijd. De woning, het gebruik, de bestaande installatie en het budget moeten eerst worden beoordeeld.'],
      ['q' => 'Werkt een warmtepomp ook voor winterverwarming?', 'a' => 'Ja, het kan een efficiente verwarmingsoplossing zijn als de warmtepomp correct gedimensioneerd is.'],
      ['q' => 'Kan het worden gecombineerd met andere verbeteringen?', 'a' => 'Ja. Soms is het zinvol ook isolatie, regeling of afgiftesystemen te overwegen.'],
    ],
    'cta_event'     => 'cta_quote_service_heatpump_detail',
    'service_type'  => 'Warmtepomp en aerothermie',
  ],
  '/nl/diensten/zonneboiler-zonneenergie/' => [
    'slug'          => 'zonneboiler-zonneenergie',
    'path'          => '/nl/diensten/zonneboiler-zonneenergie/',
    'breadcrumb'    => 'Zonneboiler &amp; zonne-energie',
    'title'         => 'Zonneboiler en thermische zonne-energie in Benidorm en Marina Baixa | +QUECLIMA',
    'description'   => 'Thermische zonne-energiesystemen in Benidorm en de Marina Baixa voor warm tapwater en energie-ondersteuning in woningen en bedrijven.',
    'h1'            => 'Zonneboiler en thermische zonne-energie in Benidorm en de Marina Baixa',
    'subtitle'      => 'Wij beoordelen thermische zonne-energieinstallaties wanneer het verbruik en de beschikbare ruimte het rechtvaardigen.',
    'hero_image'    => '/assets/img/services/service-energia-solar-termica.webp',
    'hero_alt'      => 'Thermische zonne-energie voor warm tapwater',
    'visual_slot'   => 'servicio-solar-termica-hero',
    'image_position'=> 'right center',
    'support_image' => [
      'src'     => '/assets/img/services/service-detail-energia-solar-termica.png',
      'alt'     => 'Thermische zonnepanelen op een dak',
      'caption' => '',
    ],
    'intro_title'   => 'Zonne-ondersteuning voor warm tapwater',
    'intro'         => 'Thermische zonne-energie kan een deel van de warmtapwatervraag in woningen, kleine gemeenschapsinstallaties of bedrijven dekken. Om te bepalen of het zinvol is, moeten wij het verbruik, de orientatie, de beschikbare dakoppervlakte, de integratie en de onderhoudseisen beoordelen.',
    'bullets_title' => 'Wat wij beoordelen',
    'bullets'       => [
      'Gemiddeld warmtapwaterverbruik en gebruikspatronen.',
      'Orientatie, beschaduwing en beschikbare dakoppervlakte.',
      'Integratie met opslag en het bestaande systeem.',
      'Bereikbaarheid voor onderhoud en toekomstige inspecties.',
      'Balans tussen investering, verwachte besparing en systeemlevensduur.',
    ],
    'when_title'    => 'Wanneer het een goede keuze kan zijn',
    'when_items'    => [
      'In woningen met stabiel warmtapwaterverbruik.',
      'In bedrijven of logies met regelmatige warmtapwaterbehoefte.',
      'Bij een goede orientatie en voldoende dakoppervlakte.',
      'Wanneer energie-ondersteuning wordt gezocht zonder onrealistische spaarbelooften.',
    ],
    'process_title' => 'Hoe wij werken',
    'process_items' => [
      'Wij beoordelen het verbruik, de locatie en het huidige systeem.',
      'Wij beoordelen of thermische zonne-energie past of dat een andere optie beter is.',
      'Wij stellen een onderhoudsvriendelijke oplossing voor afgestemd op het werkelijke gebruik.',
    ],
    'zones_text'    => 'Wij voeren thermische zonne-energieprojecten uit in Benidorm, Altea, Calpe, Finestrat, La Nucia en de provincie Alicante.',
    'faq'           => [
      ['q' => 'Wekt thermische zonne-energie elektriciteit op?', 'a' => 'Nee. Thermische zonne-energie is gericht op warm tapwater. Voor elektriciteitsopwekking worden andere oplossingen onderzocht.'],
      ['q' => 'Is onderhoud vereist?', 'a' => 'Ja. Net als elke installatie moeten het systeem en de onderdelen periodiek worden geïnspecteerd.'],
      ['q' => 'Is het geschikt voor elke woning?', 'a' => 'Niet altijd. Het hangt af van verbruik, orientatie, beschaduwing en compatibiliteit met het bestaande systeem.'],
    ],
    'cta_event'     => 'cta_quote_service_solar_detail',
    'service_type'  => 'Thermische zonne-energie',
  ],
];