<?php
declare(strict_types=1);

return [
  '/no/tjenester/installasjon-av-aircondition/' => [
    'slug'          => 'installasjon-av-aircondition',
    'path'          => '/no/tjenester/installasjon-av-aircondition/',
    'breadcrumb'    => 'Installasjon av aircondition',
    'title'         => 'Installasjon av aircondition i Benidorm og Marina Baixa | +QUECLIMA',
    'description'   => 'Profesjonell installasjon av aircondition i Benidorm og Marina Baixa for boliger, ferieleiligheter og næringsbygg. Befaring inkludert og tydelig tilbud.',
    'h1'            => 'Installasjon av aircondition i Benidorm og Marina Baixa',
    'subtitle'      => 'Vi installerer split-, multisplit- og kanalanlegg etter befaring, effektberegning og omhyggelig idriftsettelse.',
    'hero_image'    => '/assets/img/services/service-instalacion-aire-acondicionado.webp',
    'hero_alt'      => 'Installasjon av aircondition i en bolig',
    'visual_slot'   => 'servicio-instalacion-hero',
    'image_position'=> 'right center',
    'support_image' => [
      'src'     => '/assets/img/services/service-detail-instalacion-aire-acondicionado.png',
      'alt'     => 'Installasjon av innvendig og utvendig enhet',
      'caption' => '',
    ],
    'intro_title'   => 'En installasjon tilpasset faktisk bruk',
    'intro'         => 'Før vi anbefaler et produkt, vurderer vi boligen: areal, orientering, isolasjon, bruksmønster, plassering av uteenhet, kondensvannshåndtering og mulige støyproblemer. Målet er et system som kjøler effektivt, bruker nøyaktig det nødvendige og gir daglig komfort.',
    'bullets_title' => 'Hva vi tar hensyn til',
    'bullets'       => [
      'Riktig kapasitet for rommet, bruken og orienteringen.',
      'Optimal plassering av innvendig og utvendig enhet.',
      'Rørtrasé, kondensvannshåndtering og ryddig utførelse.',
      'Støynivå, energiforbruk og enkel vedlikehold.',
      'Idriftsettelse, brukerveiledning og garanti.',
    ],
    'when_title'    => 'Når installere eller bytte ut',
    'when_items'    => [
      'Når boligen ikke oppnår komfortabel temperatur om sommeren.',
      'Når dagens anlegg bruker for mye strøm eller svikter ofte.',
      'I ferieleiligheter der pålitelighet og lavt støynivå er avgjørende.',
      'I næringsbygg som brukes intensivt i høysesongen.',
    ],
    'process_title' => 'Slik jobber vi',
    'process_items' => [
      'Vi lytter til ønskene dine og vurderer lokasjonen.',
      'Vi beregner en realistisk løsning uten overdimensjonering.',
      'Vi installerer nøye, tester systemet og forklarer betjeningen.',
    ],
    'zones_text'    => 'Vi utfører installasjoner i Benidorm, Altea, Calpe, Finestrat, La Nucia og andre steder i Marina Baixa.',
    'faq'           => [
      ['q' => 'Hva er best: split, multisplit eller kanal?', 'a' => 'Det avhenger av boligen, rommene som skal kjøles og eventuelle forinstallerte løsninger. Vi vurderer dette før tilbudet.'],
      ['q' => 'Kan det installeres i ferieleiligheter?', 'a' => 'Ja. Da legger vi ekstra vekt på støy, energiforbruk, enkel betjening og pålitelighet.'],
      ['q' => 'Er befaring nødvendig?', 'a' => 'Anbefales når det er spørsmål om kapasitet, plassering av enheter eller rørtrasé.'],
    ],
    'cta_event'     => 'cta_quote_service_install_detail',
    'service_type'  => 'Installasjon av aircondition',
  ],
  '/no/tjenester/vedlikehold-av-klimaanlegg/' => [
    'slug'          => 'vedlikehold-av-klimaanlegg',
    'path'          => '/no/tjenester/vedlikehold-av-klimaanlegg/',
    'breadcrumb'    => 'Vedlikehold av klimaanlegg',
    'title'         => 'Vedlikehold av klimaanlegg i Benidorm og Marina Baixa | +QUECLIMA',
    'description'   => 'Vedlikehold av klimaanlegg i Benidorm og Marina Baixa: filtervask, enhetsgjennomgang, drenasjekontroll og klargjøring for sommersesongen.',
    'h1'            => 'Vedlikehold av klimaanlegg i Benidorm og Marina Baixa',
    'subtitle'      => 'Vi utfører service på klimaanlegg for å redusere risikoen for driftsstans og forberede systemet til sommeren.',
    'hero_image'    => '/assets/img/services/service-mantenimiento-climatizacion.webp',
    'hero_alt'      => 'Vedlikehold og gjennomgang av klimaanlegg',
    'visual_slot'   => 'servicio-mantenimiento-hero',
    'image_position'=> 'right center',
    'support_image' => [
      'src'     => '/assets/img/services/service-detail-mantenimiento-climatizacion.png',
      'alt'     => 'Teknisk service og vedlikehold av klimaanlegg',
      'caption' => '',
    ],
    'intro_title'   => 'Vedlikehold forlenger levetiden',
    'intro'         => 'Et skittent eller dårlig vedlikeholdt anlegg kjøler dårligere, bruker mer energi og svikter gjerne på det verste tidspunktet. I boliger, ferieleiligheter og næringsbygg sjekker vi de vanligste svake punktene og informerer deg tydelig om rengjøring, justering eller reparasjon.',
    'bullets_title' => 'Hva vi kontrollerer',
    'bullets'       => [
      'Filtervask og generell tilstandsvurdering.',
      'Sjekk av varmevekslere, kondensvannsdrenasje og mulige tette avløp.',
      'Visuell kontroll av uteenheter og ventilasjon.',
      'Lyder, vibrasjoner, lukt eller vannlekkasjer.',
      'Bruksanbefalinger for å redusere forbruk og slitasje.',
    ],
    'when_title'    => 'Når planlegge vedlikehold',
    'when_items'    => [
      'Før varmesesongen, særlig for bygg med høy belastning.',
      'Når anlegget kjøler dårligere eller bruker lengre tid på å nå ønsket temperatur.',
      'Ved lukt, drypping, lyder eller vibrasjoner.',
      'I ferieleiligheter og næringsbygg med mange brukssykluser.',
    ],
    'process_title' => 'Slik jobber vi',
    'process_items' => [
      'Vi gjennomgår anlegget og noterer rapporterte symptomer.',
      'Vi rengjør og kontrollerer kritiske tilgjengelige punkter.',
      'Vi melder om alt er i orden eller om reparasjon er anbefalt.',
    ],
    'zones_text'    => 'Vi utfører vedlikehold i Benidorm, Altea, Calpe, Finestrat, La Nucia og nærliggende steder.',
    'faq'           => [
      ['q' => 'Hvor ofte bør vedlikehold utføres?', 'a' => 'Det avhenger av bruken. For boliger kan periodisk service holde; for ferieleiligheter og næringsbygg er det som regel lurt med service før hver sesong.'],
      ['q' => 'Forhindrer vedlikehold alle feil?', 'a' => 'Det kan ikke garanteres, men det hjelper med å oppdage problemer tidlig og redusere feil forårsaket av skitt og manglende vedlikehold.'],
      ['q' => 'Vedlikeholdes også uteenheter?', 'a' => 'Ja, når de er tilgjengelige og trygge å jobbe med.'],
    ],
    'cta_event'     => 'cta_quote_service_maintenance_detail',
    'service_type'  => 'Vedlikehold av klimaanlegg',
  ],
  '/no/tjenester/reparasjon-av-aircondition/' => [
    'slug'          => 'reparasjon-av-aircondition',
    'path'          => '/no/tjenester/reparasjon-av-aircondition/',
    'breadcrumb'    => 'Reparasjon av aircondition',
    'title'         => 'Reparasjon av aircondition i Benidorm og Marina Baixa | +QUECLIMA',
    'description'   => 'Reparasjon av aircondition i Benidorm og Marina Baixa: kjøler ikke, lekker vann, lager støy eller viser feilkode.',
    'h1'            => 'Reparasjon av aircondition i Benidorm og Marina Baixa',
    'subtitle'      => 'Vi diagnostiserer feil på klimaanlegg før deler byttes ut eller nytt utstyr anbefales.',
    'hero_image'    => '/assets/img/services/service-reparacion-aire-acondicionado.webp',
    'hero_alt'      => 'Reparasjon og feilsøking av aircondition',
    'visual_slot'   => 'servicio-reparacion-hero',
    'image_position'=> 'right center',
    'support_image' => [
      'src'     => '/assets/img/services/service-detail-reparacion-aire-acondicionado.png',
      'alt'     => 'Feilsøking og reparasjon av klimaanlegg',
      'caption' => '',
    ],
    'intro_title'   => 'Tydelig diagnose før reparasjon',
    'intro'         => 'Hvis anlegget ikke kjøler, lekker vann, lager lyd eller viser en feilkode, er utskifting ikke alltid nødvendig. Vi finner den faktiske årsaken og forklarer ærlig om reparasjon, systemjustering eller utskifting er fornuftig.',
    'bullets_title' => 'Vanlige feil',
    'bullets'       => [
      'Anlegget kjøler ikke eller bruker for lang tid på å nå temperatur.',
      'Drypping, vannlekkasjer eller drenasjeproblem.',
      'Lyder, vibrasjoner eller uregelmessig drift.',
      'Feilkoder på display eller uventede avslag.',
      'Dårlig ytelse på grunn av skitt, slitasje eller forbedrings­behov i installasjonen.',
    ],
    'when_title'    => 'Når bestille feilsøking',
    'when_items'    => [
      'Før kjøp av nytt anlegg når du ikke kjenner årsaken.',
      'Når luften er varm eller anlegget går kontinuerlig uten å stoppe.',
      'Ved vannflekker på vegg, gulv eller i kondensatbakken.',
      'Når støy eller vibrasjoner har endret seg fra normalt.',
    ],
    'process_title' => 'Slik jobber vi',
    'process_items' => [
      'Vi noterer symptomene og gjennomgår anlegget.',
      'Vi finner årsaken og forklarer alternativene.',
      'Vi reparerer om det er fornuftig; hvis ikke, anbefaler vi et alternativ.',
    ],
    'zones_text'    => 'Vi utfører reparasjoner i Benidorm, Altea, Calpe, Finestrat, La Nucia og andre steder i Marina Baixa.',
    'faq'           => [
      ['q' => 'Reparere eller bytte ut?', 'a' => 'Det avhenger av anleggets alder, feiltype og kostnad. Vi vurderer først, deretter gir vi et tydelig råd.'],
      ['q' => 'Kan dere sjekke et lekende anlegg?', 'a' => 'Ja. Årsaken kan ligge i drenasjen, skitt, helling eller systemets funksjon.'],
      ['q' => 'Service for ferieleiligheter?', 'a' => 'Ja, særlig når anlegget raskt og pålitelig må tilbake i drift.'],
    ],
    'cta_event'     => 'cta_quote_service_repair_detail',
    'service_type'  => 'Reparasjon av aircondition',
  ],
  '/no/tjenester/varmepumpe-aerotermi/' => [
    'slug'          => 'varmepumpe-aerotermi',
    'path'          => '/no/tjenester/varmepumpe-aerotermi/',
    'breadcrumb'    => 'Varmepumpe &amp; aerotermi',
    'title'         => 'Varmepumpe og aerotermi i Benidorm og Marina Baixa | +QUECLIMA',
    'description'   => 'Varmepumpe- og aerotermiløsninger i Benidorm og Marina Baixa for effektiv oppvarming, helårs klimakontroll og energiforbedring.',
    'h1'            => 'Varmepumpe og aerotermi i Benidorm og Marina Baixa',
    'subtitle'      => 'Vi vurderer varmepumpe- og aerotermiløsninger kun når de faktisk passer for boligen, bruken og sparemålene.',
    'hero_image'    => '/assets/img/services/service-aerotermia-bomba-calor.webp',
    'hero_alt'      => 'Varmepumpe og aerotermi for en bolig',
    'visual_slot'   => 'servicio-aerotermia-hero',
    'image_position'=> 'left center',
    'support_image' => [
      'src'     => '/assets/img/services/service-detail-aerotermia-bomba-calor.png',
      'alt'     => 'Installasjon av varmepumpe i en bolig',
      'caption' => '',
    ],
    'intro_title'   => 'Effektivitet etter grundig vurdering',
    'intro'         => 'En varmepumpe kan være en utmerket løsning for oppvarming, kjøling og energiforbedring, men hver situasjon er ulik. Vi vurderer boligen, isolasjonen, bruksmønsteret, eksisterende varmeanlegg og forventningene før vi anbefaler et alternativ.',
    'bullets_title' => 'Hva vi vurderer',
    'bullets'       => [
      'Type bolig, isolasjon og areal som skal klimatiseres.',
      'Faktisk bruk vinter, sommer og overgangssesonger.',
      'Kompatibilitet med eksisterende systemer eller fremtidig utvidelse.',
      'Tilgjengelig plass til utstyr og vedlikeholdskrav.',
      'Komfortmål, energiforbruk og realistisk budsjett.',
    ],
    'when_title'    => 'Når det kan være fornuftig',
    'when_items'    => [
      'I eneboliger som ønsker bedre komfort og lavere energikostnader.',
      'Ved energirenovering eller systemskifte.',
      'For å bruke en effektiv enhet både til kjøling og oppvarming.',
      'Når det er tid til å vurdere installasjonen ordentlig.',
    ],
    'process_title' => 'Slik jobber vi',
    'process_items' => [
      'Vi lytter til ønskene dine, vurderer boligen og eksisterende system.',
      'Vi forklarer om varmepumpe passer eller om det finnes et enklere alternativ.',
      'Vi lager et forslag basert på komfort-, energi- og vedlikeholdskriterier.',
    ],
    'zones_text'    => 'Vi vurderer varmepumpeløsninger i Benidorm, Altea, Calpe, Finestrat, La Nucia og den nordlige Costa Blanca.',
    'faq'           => [
      ['q' => 'Er aerotermi alltid lønnsomt?', 'a' => 'Ikke alltid. Boligen, bruken, eksisterende installasjon og budsjettet må først vurderes.'],
      ['q' => 'Fungerer varmepumpe til vinteroppvarming?', 'a' => 'Ja, ved riktig dimensjonering kan det være en effektiv oppvarmingsløsning.'],
      ['q' => 'Kan det kombineres med andre forbedringer?', 'a' => 'Ja. Noen ganger er det fornuftig å vurdere isolasjon, styring eller varmeanlegg i tillegg.'],
    ],
    'cta_event'     => 'cta_quote_service_heatpump_detail',
    'service_type'  => 'Varmepumpe og aerotermi',
  ],
  '/no/tjenester/solvarme/' => [
    'slug'          => 'solvarme',
    'path'          => '/no/tjenester/solvarme/',
    'breadcrumb'    => 'Solvarme',
    'title'         => 'Solvarme og solfangere i Benidorm og Marina Baixa | +QUECLIMA',
    'description'   => 'Termiske solvarme­systemer i Benidorm og Marina Baixa for varmtvann og energistøtte i boliger og næringsbygg.',
    'h1'            => 'Solvarme og solfangere i Benidorm og Marina Baixa',
    'subtitle'      => 'Vi vurderer termiske solvarmeanlegg når forbruket og tilgjengelig areal rettferdiggjør det.',
    'hero_image'    => '/assets/img/services/service-energia-solar-termica.webp',
    'hero_alt'      => 'Solfangere for varmtvannsproduksjon',
    'visual_slot'   => 'servicio-solar-termica-hero',
    'image_position'=> 'right center',
    'support_image' => [
      'src'     => '/assets/img/services/service-detail-energia-solar-termica.png',
      'alt'     => 'Termiske solpaneler på et tak',
      'caption' => '',
    ],
    'intro_title'   => 'Solstøtte for varmtvann',
    'intro'         => 'Solvarme kan dekke en del av varmtvannsbehovet i boliger, små fellesanlegg eller næringsbygg. For å vurdere om det er fornuftig, ser vi på forbruk, orientering, tilgjengelig takareal, integrasjon og vedlikeholdskrav.',
    'bullets_title' => 'Hva vi vurderer',
    'bullets'       => [
      'Gjennomsnittlig varmtvannsforbruk og bruksmønstre.',
      'Orientering, skyggefall og tilgjengelig takareal.',
      'Integrasjon med tank og eksisterende system.',
      'Tilgjengelighet for vedlikehold og fremtidige inspeksjoner.',
      'Balanse mellom investering, forventet besparelse og systemets levetid.',
    ],
    'when_title'    => 'Når det kan være et godt valg',
    'when_items'    => [
      'I boliger med stabilt varmtvannsforbruk.',
      'I næringsbygg eller overnattingssteder med jevnlig varmtvannsbehov.',
      'Med god orientering og tilstrekkelig takareal.',
      'Når man søker energistøtte uten urealistiske sparingsløfter.',
    ],
    'process_title' => 'Slik jobber vi',
    'process_items' => [
      'Vi vurderer forbruk, lokasjon og eksisterende system.',
      'Vi vurderer om solvarme passer eller om et annet alternativ er bedre.',
      'Vi foreslår en vedlikeholdsvennlig løsning tilpasset faktisk bruk.',
    ],
    'zones_text'    => 'Vi gjennomfører solvarmeprosjekter i Benidorm, Altea, Calpe, Finestrat, La Nucia og Alicante-provinsen.',
    'faq'           => [
      ['q' => 'Produserer solvarme elektrisitet?', 'a' => 'Nei. Termiske solsystemer er rettet mot varmtvann. For strømproduksjon finnes andre løsninger.'],
      ['q' => 'Kreves det vedlikehold?', 'a' => 'Ja. Som alle anlegg må systemet og komponentene sjekkes periodisk.'],
      ['q' => 'Passer det for alle boliger?', 'a' => 'Ikke alltid. Det avhenger av forbruk, orientering, skygge og kompatibilitet med eksisterende system.'],
    ],
    'cta_event'     => 'cta_quote_service_solar_detail',
    'service_type'  => 'Solvarme',
  ],
];
