<?php
return [
  // Values below were observed in Google's public business panel for +QUECLIMA.
  // Keep this file manual for now (no API/runtime calls).
  'rating' => '5,0',
  'review_count' => 70,
  'google_url' => 'https://share.google/2YL5e0lFenNMWZNk1',
  'updated_at' => '2026-05-29',

  'reviews' => [
    [
      'name' => 'Jorge Donat Olcina',
      'meta' => 'Local Guide · 83 reseñas · 3624 fotos',
      'date' => '4 jun 2025',
      'stars' => 5,
      'text' => 'Tanto Dani como Fabián han hecho un trabajo excelente. Muy profesionales, limpios y puntuales. Me subieron el aparato exterior y me dejaron la instalación perfecta. ¡Los recomiendo sin duda alguna!',
      'has_photo' => true,
    ],
    [
      'name' => 'Andrés Adán Millán',
      'meta' => '2 reseñas · 1 foto',
      'date' => 'Hace 8 semanas',
      'stars' => 5,
      'text' => 'Muy contento con el servicio de Más que Clima en Benidorm. Instalación rápida, profesionales atentos y todo funcionando perfecto desde el primer día. Sin duda los recomiendo si necesitas un aire acondicionado.',
      'has_photo' => true,
    ],
    [
      'name' => 'Leonor Rocamora',
      'meta' => '3 reseñas · 1 foto',
      'date' => 'Hace 44 semanas',
      'stars' => 5,
      'text' => 'Muy profesionales, te aconsejan con las mejores marcas y la instalación muy rápida. Ya van varias veces que he trabajado con ellos y son un 10. 100% recomendables sin duda.',
      'has_photo' => true,
    ],
    [
      'name' => 'Nuria Araujo',
      'meta' => 'Local Guide · 26 reseñas · 13 fotos',
      'date' => '7 sept 2023',
      'stars' => 5,
      'text' => 'Muy profesionales, muy humanos. Estoy contentísima con los dos aires que me han colocado. Siempre están a disposición del cliente. Les estoy súper agradecida.',
      'has_photo' => true,
    ],
    [
      'name' => 'Mario van der Weerd',
      'meta' => 'Local Guide · 14 reseñas · 20 fotos',
      'date' => '28 ago 2023',
      'stars' => 5,
      'text' => 'Todo perfecto! Rápido, limpio y muy profesional. Yuri y Mario, Bar El Papagayo Benidorm.',
      'has_photo' => true,
    ],
    [
      'name' => 'Katia P.',
      'meta' => 'Local Guide · 9 reseñas · 19 fotos',
      'date' => '31 may 2022',
      'stars' => 5,
      'text' => 'Han instalado mi aire acondicionado en Dénia y encantada. Muy buenos profesionales, rápidos y todo limpio y recogido. Repetiría sin dudar!',
      'has_photo' => true,
    ],
    [
      'name' => 'Sebastiano Russo',
      'meta' => 'Local Guide · 30 reseñas · 35 fotos',
      'date' => '27 may 2022',
      'stars' => 5,
      'text' => 'Azienda che lavora molto bene, puntuale, precisa e molto competente. I ragazzi sono gentili e professionali, li raccomando a coloro che necessitano di un loro intervento.',
      'has_photo' => true,
    ],
    [
      'name' => 'Aneta Sobrino',
      'meta' => 'Local Guide · 16 reseñas · 1 foto',
      'date' => 'Hace 7 semanas',
      'stars' => 5,
      'text' => 'Excelente equipo, excelente trabajo!!! Dos veces me han hecho las cosas perfectamente! Gracias.',
      'has_photo' => true,
    ],
    [
      'name' => 'Dragos Fatu',
      'meta' => '9 reseñas · 2 fotos',
      'date' => 'Hace 50 semanas',
      'stars' => 5,
      'text' => 'Todo muy bien, me ha puesto el aire rápido y eficaz, me ha salvado del infierno del verano 🫠🫠',
      'has_photo' => true,
    ],
    [
      'name' => 'Irenka Z',
      'meta' => 'Local Guide · 111 reseñas · 86 fotos',
      'date' => '28 ene 2025',
      'stars' => 5,
      'text' => 'Excellent service—fast, efficient, and highly knowledgeable. A professional and friendly team. Highly recommend.',
      'has_photo' => true,
    ],
    [
      'name' => 'J Marbach',
      'meta' => '5 reseñas',
      'date' => '27 feb 2025',
      'stars' => 5,
      'text' => 'Teníamos un problema con nuestro aire acondicionado. Dani ha llegado rápido y ha solucionado perfecto. Precio/calidad 100%. Ya le hemos recomendado a nuestros vecinos.',
      'has_photo' => false,
    ],
    [
      'name' => 'Julián Andrés Guarin Villegas',
      'meta' => '5 reseñas · 1 foto',
      'date' => '17 mar 2022',
      'stars' => 5,
      'text' => 'Pedí presupuesto para cambiar el termo. Lo instalaron al día siguiente. Económico y muy rápido. Contento con su trabajo.',
      'has_photo' => true,
    ],
  ],
];
