<?php
declare(strict_types=1);

return [
  '/de/dienstleistungen/' => [
    'slug'           => 'dienstleistungen',
    'hub_type'       => 'services',
    'lang'           => 'de',
    'title'          => 'Klimaanlagen-Service in Benidorm und Marina Baixa | +QUECLIMA',
    'description'    => 'Klimaanlage montieren, warten und reparieren in Benidorm und der Marina Baixa. Fachkundige Beratung, zertifizierte Techniker und echte 3-Jahres-Garantie.',
    'h1'             => 'Klimaanlagen-Service in Benidorm und der Marina Baixa',
    'breadcrumb'     => 'Dienstleistungen',
    'hero_image'     => '/assets/img/heroes/hub-servicios-climatizacion.webp',
    'hero_alt'       => 'Klimaanlagen-Service in Benidorm und Marina Baixa',
    'visual_slot'    => 'hub-servicios-hero',
    'image_position' => 'center center',
    'hub_intro'      => 'Wir montieren, warten und reparieren Klimaanlagen, Heizungen und Energiesysteme für Wohnungen, Ferienwohnungen, Gemeinschaftsanlagen und Gewerbebetriebe an der Costa Blanca.',
    'hub_kicker'     => 'Dienstleistungen',
    'hub_h2'         => 'Klimatisierungslösungen',
    'hub_p'          => 'Wir arbeiten mit Split-, Multi-Split-, Kanal- und Wärmepumpensystemen. Vor jeder Montage besichtigen wir das Objekt, um eine effiziente Lösung für den tatsächlichen Bedarf zu empfehlen.',
    'hub_zones_kicker' => 'Servicegebiet',
    'hub_zones_h2'   => 'Lokaler Service in der Marina Baixa',
    'hub_zones_p'    => 'Wir arbeiten täglich in Benidorm, Altea, Calpe, Finestrat und La Nucía und fahren auf Anfrage auch in umliegende Orte.',
    'hub_zones_all'  => 'Alle Gebiete',
  ],
  '/de/gebiete/' => [
    'slug'           => 'gebiete',
    'hub_type'       => 'areas',
    'lang'           => 'de',
    'title'          => 'Klimaanlage-Servicegebiete in Alicante | +QUECLIMA',
    'description'    => 'Klimaanlage-Service in Benidorm, Altea, Calpe, Finestrat, La Nucía und anderen Gemeinden der Marina Baixa und der Provinz Alicante.',
    'h1'             => 'Klimaanlage-Servicegebiete in Alicante',
    'breadcrumb'     => 'Gebiete',
    'hero_image'     => '/assets/img/heroes/hub-zonas-marina-baixa.webp',
    'hero_alt'       => 'Klimaanlage-Servicegebiete in Alicante',
    'visual_slot'    => 'hub-zonas-hero',
    'image_position' => 'center center',
    'hub_intro'      => 'Von Benidorm aus bedienen wir die Marina Baixa, die nördliche Costa Blanca und die Provinz Alicante mit kurzer Anfahrtszeit und persönlicher Beratung.',
    'hub_kicker'     => 'Abdeckung',
    'hub_h2'         => 'Orte, in denen wir tätig sind',
    'hub_p'          => 'Wir führen Klimaanlagen-Installation, Wartung und Reparatur in diesen Gemeinden und deren Umgebung durch.',
    'hub_context_kicker' => 'Lokale Priorität',
    'hub_context_h2'    => 'Benidorm, Marina Baixa und nördliche Costa Blanca',
    'hub_context_p'     => 'Jedes Gebiet hat unterschiedliche Anforderungen: Ferienwohnungen in Benidorm, Strandhäuser in Altea und Calpe, Neubauten in Finestrat und Villen in La Nucía. Wir passen die Lösung an jedes Objekt und seinen Verwendungszweck an.',
    'hub_cta'        => 'Angebot anfordern',
    'hub_select_p'   => 'Wählen Sie einen Ort aus, um die lokale Seite anzuzeigen.',
  ],
  '/de/ratgeber/' => [
    'slug'           => 'ratgeber',
    'hub_type'       => 'guides',
    'lang'           => 'de',
    'title'          => 'Klimaanlage-Ratgeber für die Costa Blanca | +QUECLIMA',
    'description'    => 'Praxistipps zur Auswahl, Wartung und Optimierung von Klimaanlagen in Benidorm und an der Costa Blanca: Effizienz, Wärmepumpen, Solarthermie und mehr.',
    'h1'             => 'Klimaanlage-Ratgeber für die Costa Blanca',
    'breadcrumb'     => 'Ratgeber',
    'hero_image'     => '/assets/img/heroes/hub-guias-climatizacion.webp',
    'hero_alt'       => 'Klimaanlage-Ratgeber und Tipps',
    'visual_slot'    => 'hub-guias-hero',
    'image_position' => 'center center',
    'hub_intro'      => 'Praxistipps zur Auswahl, Wartung und optimalen Nutzung Ihrer Klimaanlage an der Costa Blanca.',
    'hub_kicker'     => 'Ratgeber',
    'hub_h2'         => 'Nützliche Ratgeber-Bibliothek',
    'hub_p'          => 'Wir erstellen praxisnahe Ratgeber zu häufigen Kundenfragen: Stromverbrauch, benötigte Leistung, Wartung, Wärmepumpen, Aerothermie sowie Installation in Wohnungen, Ferienwohnungen und Gemeinschaftsanlagen.',
  ],
];
