<?php
declare(strict_types=1);

return [
  '/en/services/' => [
    'slug'           => 'services',
    'hub_type'       => 'services',
    'lang'           => 'en',
    'title'          => 'Air conditioning services in Benidorm and Marina Baixa | +QUECLIMA',
    'description'    => 'Air conditioning installation, maintenance and repair in Benidorm and the Marina Baixa. Expert advice, certified technicians and a real 3-year warranty.',
    'h1'             => 'Air conditioning services in Benidorm and Marina Baixa',
    'breadcrumb'     => 'Services',
    'hero_image'     => '/assets/img/heroes/hub-servicios-climatizacion.webp',
    'hero_alt'       => 'Air conditioning services in Benidorm and Marina Baixa',
    'visual_slot'    => 'hub-servicios-hero',
    'image_position' => 'center center',
    'hub_intro'      => 'We install, maintain and repair air conditioning, heating and energy systems for homes, holiday apartments, communities and businesses on the Costa Blanca.',
    'hub_kicker'     => 'Services',
    'hub_h2'         => 'HVAC solutions',
    'hub_p'          => 'We work with split, multi-split, ducted and heat-pump systems. Before any installation we assess the property to recommend an efficient solution suited to actual use.',
    'hub_zones_kicker' => 'Service area',
    'hub_zones_h2'   => 'Local coverage in Marina Baixa',
    'hub_zones_p'    => 'We work daily in Benidorm, Altea, Calpe, Finestrat and La Nucía, and travel to other nearby localities on request.',
    'hub_zones_all'  => 'All areas',
  ],
  '/en/areas/' => [
    'slug'           => 'areas',
    'hub_type'       => 'areas',
    'lang'           => 'en',
    'title'          => 'Air conditioning service areas in Alicante | +QUECLIMA',
    'description'    => 'Local air conditioning coverage in Benidorm, Altea, Calpe, Finestrat, La Nucía and other towns in the Marina Baixa and Alicante province.',
    'h1'             => 'Air conditioning service areas in Alicante',
    'breadcrumb'     => 'Areas',
    'hero_image'     => '/assets/img/heroes/hub-zonas-marina-baixa.webp',
    'hero_alt'       => 'Air conditioning service areas in Alicante',
    'visual_slot'    => 'hub-zonas-hero',
    'image_position' => 'center center',
    'hub_intro'      => 'Based in Benidorm, we cover the Marina Baixa, the northern Costa Blanca and Alicante province with fast turnaround and close personal advice.',
    'hub_kicker'     => 'Coverage',
    'hub_h2'         => 'Towns where we provide service',
    'hub_p'          => 'We carry out air conditioning installation, maintenance and repairs in these towns and their surrounding areas.',
    'hub_context_kicker' => 'Local priority',
    'hub_context_h2'    => 'Benidorm, Marina Baixa and northern Costa Blanca',
    'hub_context_p'     => 'Each area has different needs: holiday apartments in Benidorm, seafront homes in Altea and Calpe, new builds in Finestrat and villas in La Nucía. We tailor the solution to the property and its use.',
    'hub_cta'        => 'Request a quote',
    'hub_select_p'   => 'Select a town to view the local page.',
  ],
  '/en/guides/' => [
    'slug'           => 'guides',
    'hub_type'       => 'guides',
    'lang'           => 'en',
    'title'          => 'Air conditioning guides and tips for the Costa Blanca | +QUECLIMA',
    'description'    => 'Practical guides on choosing, maintaining and getting more from your HVAC system in Benidorm and the Costa Blanca: efficiency, heat pumps, solar thermal and more.',
    'h1'             => 'Air conditioning guides and tips for the Costa Blanca',
    'breadcrumb'     => 'Guides',
    'hero_image'     => '/assets/img/heroes/hub-guias-climatizacion.webp',
    'hero_alt'       => 'Air conditioning guides and tips',
    'visual_slot'    => 'hub-guias-hero',
    'image_position' => 'center center',
    'hub_intro'      => 'Practical advice on choosing, maintaining and getting more from your air conditioning system on the Costa Blanca.',
    'hub_kicker'     => 'Guides',
    'hub_h2'         => 'Useful guide library',
    'hub_p'          => 'We are preparing practical guides based on real customer questions: energy consumption, required output, maintenance, heat pumps, aerothermal systems, and installation in homes, holiday apartments and communities.',
  ],
];
