<?php
declare(strict_types=1);

return [
  '/nl/diensten/' => [
    'slug'           => 'diensten',
    'hub_type'       => 'services',
    'lang'           => 'nl',
    'title'          => 'Airco-diensten in Benidorm en Marina Baixa | +QUECLIMA',
    'description'    => 'Airconditioning installeren, onderhouden en repareren in Benidorm en de Marina Baixa. Eerlijk advies, gecertificeerde monteurs en 3 jaar garantie.',
    'h1'             => 'Airco-diensten in Benidorm en de Marina Baixa',
    'breadcrumb'     => 'Diensten',
    'hero_image'     => '/assets/img/heroes/hub-servicios-climatizacion.webp',
    'hero_alt'       => 'Airco-diensten in Benidorm en Marina Baixa',
    'visual_slot'    => 'hub-servicios-hero',
    'image_position' => 'center center',
    'hub_intro'      => 'Wij installeren, onderhouden en repareren airconditioningsystemen, verwarmingsinstallaties en energiesystemen voor woningen, vakantieappartementen, VvE\'s en bedrijven aan de Costa Blanca.',
    'hub_kicker'     => 'Diensten',
    'hub_h2'         => 'Klimaatoplossingen',
    'hub_p'          => 'Wij werken met split-, multi-split-, kanaal- en warmtepompsystemen. Vóór elke installatie beoordelen we de woning om een efficiënte oplossing aan te bevelen die aansluit op het werkelijke gebruik.',
    'hub_zones_kicker' => 'Servicegebied',
    'hub_zones_h2'   => 'Lokale service in de Marina Baixa',
    'hub_zones_p'    => 'We werken dagelijks in Benidorm, Altea, Calpe, Finestrat en La Nucía en rijden op aanvraag ook naar andere nabijgelegen plaatsen.',
    'hub_zones_all'  => 'Alle gebieden',
  ],
  '/nl/gebieden/' => [
    'slug'           => 'gebieden',
    'hub_type'       => 'areas',
    'lang'           => 'nl',
    'title'          => 'Airco-servicegebieden in Alicante | +QUECLIMA',
    'description'    => 'Airco-service in Benidorm, Altea, Calpe, Finestrat, La Nucía en andere plaatsen in de Marina Baixa en de provincie Alicante.',
    'h1'             => 'Airco-servicegebieden in Alicante',
    'breadcrumb'     => 'Gebieden',
    'hero_image'     => '/assets/img/heroes/hub-zonas-marina-baixa.webp',
    'hero_alt'       => 'Airco-servicegebieden in Alicante',
    'visual_slot'    => 'hub-zonas-hero',
    'image_position' => 'center center',
    'hub_intro'      => 'Vanuit Benidorm bedienen we de Marina Baixa, de noordelijke Costa Blanca en de provincie Alicante met snelle responstijden en persoonlijk advies.',
    'hub_kicker'     => 'Dekking',
    'hub_h2'         => 'Plaatsen waar wij actief zijn',
    'hub_p'          => 'Wij voeren airco-installatie, -onderhoud en -reparaties uit in deze plaatsen en de omgeving.',
    'hub_context_kicker' => 'Lokale prioriteit',
    'hub_context_h2'    => 'Benidorm, Marina Baixa en noordelijke Costa Blanca',
    'hub_context_p'     => 'Elke regio heeft andere behoeften: vakantieappartementen in Benidorm, zeezichtwoningen in Altea en Calpe, nieuwbouw in Finestrat en villa\'s in La Nucía. Wij passen de oplossing aan de woning en het gebruik aan.',
    'hub_cta'        => 'Offerte aanvragen',
    'hub_select_p'   => 'Selecteer een plaats om de lokale pagina te bekijken.',
  ],
  '/nl/gidsen/' => [
    'slug'           => 'gidsen',
    'hub_type'       => 'guides',
    'lang'           => 'nl',
    'title'          => 'Airco-gidsen en tips voor de Costa Blanca | +QUECLIMA',
    'description'    => 'Praktische gidsen over het kiezen, onderhouden en optimaal benutten van uw airconditioningsysteem in Benidorm en aan de Costa Blanca.',
    'h1'             => 'Airco-gidsen en tips voor de Costa Blanca',
    'breadcrumb'     => 'Gidsen',
    'hero_image'     => '/assets/img/heroes/hub-guias-climatizacion.webp',
    'hero_alt'       => 'Airco-gidsen en tips',
    'visual_slot'    => 'hub-guias-hero',
    'image_position' => 'center center',
    'hub_intro'      => 'Praktische tips over het kiezen, onderhouden en optimaal benutten van uw airconditioningsysteem aan de Costa Blanca.',
    'hub_kicker'     => 'Gidsen',
    'hub_h2'         => 'Nuttige gidsenbibliotheek',
    'hub_p'          => 'We bereiden praktische gidsen voor op basis van veelgestelde vragen van klanten: energieverbruik, benodigde capaciteit, onderhoud, warmtepompen, aerothermie en installatie in woningen, vakantieappartementen en VvE\'s.',
  ],
];
