<?php
declare(strict_types=1);

return [
  '/no/tjenester/' => [
    'slug'           => 'tjenester',
    'hub_type'       => 'services',
    'lang'           => 'no',
    'title'          => 'Klimaanleggtjenester i Benidorm og Marina Baixa | +QUECLIMA',
    'description'    => 'Montering, service og reparasjon av klimaanlegg i Benidorm og Marina Baixa. Faglig rådgivning, sertifiserte teknikere og ekte 3-årsgaranti.',
    'h1'             => 'Klimaanleggtjenester i Benidorm og Marina Baixa',
    'breadcrumb'     => 'Tjenester',
    'hero_image'     => '/assets/img/heroes/hub-servicios-climatizacion.webp',
    'hero_alt'       => 'Klimaanleggtjenester i Benidorm og Marina Baixa',
    'visual_slot'    => 'hub-servicios-hero',
    'image_position' => 'center center',
    'hub_intro'      => 'Vi monterer, vedlikeholder og reparerer klimaanlegg, varmesystemer og energiinstallasjoner for boliger, ferieleiligheter, borettslag og bedrifter på Costa Blanca.',
    'hub_kicker'     => 'Tjenester',
    'hub_h2'         => 'Klimaanleggløsninger',
    'hub_p'          => 'Vi arbeider med split-, multi-split-, kanal- og varmepumpesystemer. Før montering besøker vi eiendommen for å anbefale en effektiv løsning tilpasset faktisk bruk.',
    'hub_zones_kicker' => 'Serviceområde',
    'hub_zones_h2'   => 'Lokal dekning i Marina Baixa',
    'hub_zones_p'    => 'Vi arbeider daglig i Benidorm, Altea, Calpe, Finestrat og La Nucía og reiser på forespørsel til andre nærliggende steder.',
    'hub_zones_all'  => 'Alle områder',
  ],
  '/no/omrader/' => [
    'slug'           => 'omrader',
    'hub_type'       => 'areas',
    'lang'           => 'no',
    'title'          => 'Serviceomr&aring;der for klimaanlegg i Alicante | +QUECLIMA',
    'description'    => 'Klimaanlegg-service i Benidorm, Altea, Calpe, Finestrat, La Nucía og andre steder i Marina Baixa og Alicante-provinsen.',
    'h1'             => 'Serviceområder for klimaanlegg i Alicante',
    'breadcrumb'     => 'Omr&aring;der',
    'hero_image'     => '/assets/img/heroes/hub-zonas-marina-baixa.webp',
    'hero_alt'       => 'Serviceområder for klimaanlegg i Alicante',
    'visual_slot'    => 'hub-zonas-hero',
    'image_position' => 'center center',
    'hub_intro'      => 'Med base i Benidorm dekker vi Marina Baixa, nordlige Costa Blanca og Alicante-provinsen med rask responstid og personlig rådgivning.',
    'hub_kicker'     => 'Dekning',
    'hub_h2'         => 'Steder vi betjener',
    'hub_p'          => 'Vi utfører montering, vedlikehold og reparasjon av klimaanlegg i disse stedene og omegn.',
    'hub_context_kicker' => 'Lokal prioritet',
    'hub_context_h2'    => 'Benidorm, Marina Baixa og nordlige Costa Blanca',
    'hub_context_p'     => 'Hvert område har ulike behov: ferieleiligheter i Benidorm, sjøutsiktsboliger i Altea og Calpe, nybygg i Finestrat og villaer i La Nucía. Vi tilpasser løsningen til eiendommen og bruken.',
    'hub_cta'        => 'Be om tilbud',
    'hub_select_p'   => 'Velg et sted for å se den lokale siden.',
  ],
  '/no/guider/' => [
    'slug'           => 'guider',
    'hub_type'       => 'guides',
    'lang'           => 'no',
    'title'          => 'Klimaanlegg-guider for Costa Blanca | +QUECLIMA',
    'description'    => 'Praktiske guider om valg, vedlikehold og optimal bruk av klimaanlegg i Benidorm og på Costa Blanca: effektivitet, varmepumper, solvarme og mer.',
    'h1'             => 'Klimaanlegg-guider for Costa Blanca',
    'breadcrumb'     => 'Guider',
    'hero_image'     => '/assets/img/heroes/hub-guias-climatizacion.webp',
    'hero_alt'       => 'Klimaanlegg-guider og tips',
    'visual_slot'    => 'hub-guias-hero',
    'image_position' => 'center center',
    'hub_intro'      => 'Praktiske tips om valg, vedlikehold og optimal bruk av klimaanlegget ditt på Costa Blanca.',
    'hub_kicker'     => 'Guider',
    'hub_h2'         => 'Nyttig guidebibliotek',
    'hub_p'          => 'Vi utarbeider praktiske guider basert på vanlige kundespørsmål: energiforbruk, nødvendig effekt, vedlikehold, varmepumper, aerothermi og montering i boliger, ferieleiligheter og borettslag.',
  ],
];
